import React, { useState } from "react";

const PDC = () => {
 const videoIDs = [
 "yNnMJUBZd2w",
"D4RcqsdZi70",
"5RhYvHp-B_4",
"B5ls9H6oUpU",
"kXoA6oKlKpw",
"i39xuoQbIRM",
"fs5-K2LxlcA",
"7wAKiY0MdyY",
"OoUAwI1zpho",
"vZkPUTnfUw8",
"dDPul5mZhS8",
"UtrAhToF3cA",
"yczSI9L3oXo",
"5lVNZZrpOqU",
"iOi9h0OsXdQ",
"AFqA1m6GEok",
"0brAI99jrCg",
"quRMZ35F9BE",
"jltNffi5UNY",
"I7AD4X_-5jM",
"Kw3Q2OfxTt0",
"ua80p_qSN4E",
"1HD7J8TQPuE",
"J7uBimjj4Jo",
"qjB4CeHXzrc",
"6aRMW4p2WEc",
"nuXzddhYiDE",
"wjdBfcLSrEY",
"y0BuvfDNPQ0",
"14uTDBuVnY8",
"yES7YOqK6oA",
"vKoo0HLLE50",
"Z-QGtxlQWak",
"cCtNbaUIex4",
"RhsZg1ns2n8",
"qnaRf1iTss4",
"DM7sYJowN-A",
"oxVauLakNcY",
"mScjm34v4oQ",
"s8rsR_TStaA",
"H4hk6N5vC1Q",
"TmkTwJT79yc",
"jPCgU4ghB8Q",
"jnB-U5KBvN4",
"sTHbXeiAB_c",
"9Cd5nVCFfc0",
"dnrJlCD2MLc",
"BzAbZfT6RxQ",
"3mQr7rU4lnA",
"6O2oEQ2UwxY",
"zsJmqRY1uW0",
"TiC4P9WLzo8",
"c_YLkvk_ZXI",
"d0DbwTJUy5c",
"wH-R5ao8Wmg",
"bb_z42C-1-E",
"5fX9RfTTvqI",
"BBwgM_UNkFU",
"_f2vBo-ZDdI",
"Gj9pDC_OBQU",
"zkHs90fmVf4",
"4kEZQ9RtItk",
"A3Il3OyNoso",
"SfIQ6fLk6co",
"Q74dKFrpf_I",
"Ppblm9W51ac",
"D7AVHFA5JDQ",
"pXuloeCvcqM",
"O1HRtZmkI4E",
"Rm8vde7ly24",
"736ockPyw6k",
"T_pXdbHIWEg",
"Vw5Pj7RWyUU",
"Ws4ISTh3JgU",
"ZZRqf5jT3vs",
"OPqRzo4FLqI",
"f3feXJr2cLc",
"0Kmqp-XX_F0",
"b7lpVBTSVIU",
"1cRt9Duemew",
"2VXB7r0GKVE",
"okeuvau35mA",
"7ajS31nqD78",
"vG0Q7BNocmI",
"q6w4bf7hp_s",
"_tRMChRAqRc",
"S45i6YbfUuQ",
"X32LydcZS50",
"pa8BtYyZcrY",
"22yUGXQj1_U",
"g9cx7Jhx7oU",
"UbuLRKNTznw",
"QafVncdLd-g",
"3sGKZdVF58U",
"3FZ4c7YzioA",
"TNiS4lgcIzg",
"zoFUAC6BZUA",
"suFh1FTETRI",
"CWozCRh4Nno",
"yRjob1yPbpM",
"qckigAXWa7w",
"Vdqq8LUhGG8",
"tI7sEfdnYdE",
"e0EPWBACGiU",
"-_7kIAn82cI",
"SWt2PYiGgKQ",
"T_pGvvyjIkI",
"JNXTgrbTnGc",
"9JrC44OyIFE",
"9sd4DWragBg",
"sSU57kZhMSc",
"IFaliBPD1UY",
"uN1jdUaK0Ak",
"Ep4h3f-qySY",
"XMuSNiCO-TI",
"jPMxF_qYZdg",
"1fuRIm0Lx0Q",
"mNRcFn3KMPk",
"O5OXd_IDDRI",
"3_VERjf1sgs",
"npsZ2SBeVpA",
"xJHJbo3VnmY",
"0sRAMfPUQ58",
"CtmctzdKTcU",
"mqwUtn5cip8",
"0TzBSqENELM",
"A5SlTkKfUz0",
"LezLNMznZm4",
"BZq7j2b-7Lw",
"P4_iWrawCZs",
"emRV4juY17s",
"wOQDGvCLOs8",
"QcAY1oPozhw",
"mJSipEX5nWk",
"kAy5LHGPlRY",
"RljiuMPVoM8",
"fVsDHeBTjY0",
"b7Go0FCeJeU",
"kvBKZnQNtn8",
"2bqrG-bUcKU",
"7N6UYfUOIvM",
"bqN9kXL3dlc",
"tq353ew4gEw",
"zkF-v7kS5_o",
"ngJ2QWvMPbI",
"5QtIfoqLncQ",
"IdwpoS7YeJA",
"EIYYhwTP1jk",
"aaurfdKG-oE",
"Y8iFJVmSQIk",
"aEkDVqQDLH8",
"A1Fk-RHaSkQ",
"-oNqg6JH0eI",
"_HATc2zAhcY",
"mRJOYC73DnE",
"GIQPtGPS974",
"Cfw5EKbJHlk",
"80uvr_tdSI8",
"nHahox9pCg0",
"dSoXmaLsVYA",
"tKA38sAf8SE",
"fM3zqjci3SQ",
"rzV1iWmqtX0",
"-xUow-nafEQ",
"znkTOn0SfYU",
"sf7TNuuAIxU",
"u6dPdJjj8Kw",
"xdxHuw7Rs8k",
"ZlRqlwWioiE",
"795NrVrGXRQ",
"oP33taQEp4s",
"Ifq3K6p6RrA",
"hMeHr7zrHDs",
"mNYfiFTdsXo",
"b_VEKvST-lQ",
"9VzN_CohuNs",
"yZN_1tyOcOE",
"m9tASJ9DaTY",
"it6kiQuWdCo",
"9R3-0-Xg_Ro",
"blS_OImUJ-c",
"0d-xE2SvsSo",
"Ck6k1ulzgec",
"yVF_POXZBlw",
"srZyO_fJgp8",
"1GYU0i7zyUU",
"67HXJWd5ysQ",
"oXrbcRyXj84",
"on9FgztLyyk",
"w9ukTqSKFg0",
"xX6btp7Yn0I",
"cXZLjcx7Dsc",
"14B-3mU66Rg",
"1kvuy_t4lCM",
"0gRfPntQGqg",
"lAFGC3Q3Yk0",
"AmFHyKDqIsc",
"0nYkFji8y0E",
"2nSWjCkMGdo",
"714h9_5LPso",
"ijyVvwYE6H0",
"gX7UDbN5QE0",
"ED--r1lByl4",
"U7YwVMEHAVI",
"3OmFm-Qi7nE",
"j44UINh3JWY",
"7NKxAP-H6PE",
"gY6nUWuHfq8",
"ko65IqajDT8",
"UfeQ0OkXNj4",
"XR5g_f6dmSE",
"ZDCsLiC46S8",
"rCw-FVegWJA",
"UaUZsO-lckA",
"0USI-48ovJI",
"vshs9v83d0M",
"dWN0DzqlCZk",
"ihfm31HOYJ8",
"khmB0NoJWfA",
"t05C3pvLbsc",
"mGmPCLUZuGY",
"44-q1WwPvhc",
"IrKSx4mMK5M",
"9OK_i-n8gN8",
"uQkCar2SbVY",
"9_LaBHem4GI",
"WjOlJ2lPZOg",
"m8itztttxPE",
"blf9rfmxGvo",
"GCxCHP6QSNM",
"fDrChXcplcA",
"pAmqpID_36g",
"c9zCIPsH4R4",
"M10lkIuJmTs",
"8pwGRTnY0W0",
"2T_KpTGUcHo",
"IKJuvJGjADY",
"W1MW1dkE0ro",
"1A0grLVxY4w",
"0_kHkdgzsxM",
"6nVvbSuyNaU",
"Lf8v1kg37YY",
"lBiW4gEZNfQ",
"yBjWlHQFruM",
"YzsbxApfE60",
"RemTOQX4tsU",
"2oJzdf63LgQ",
"9I4z5JPbvgg",
"rPr6lozpfPE",
"rYKb_V0Or7A",
"DkhMTj-YEpA",
"xAPv826E_Go",
"tD2kXTJ25dA",
"qE-WNoeMNvs",
"UMG0n3DItPg",
"KjzBW4POLBE",
"24Sm_x8UZLo",
"R83RrZCjvKo",
"S-B0r5D6fHI",
"OXC95lauAjk",
"xNx2NCeISas",
"1wWiA0l2GQk",
"S7zGQWX3FZQ",
"06DQVFZtfGw",
"LyOQVvPVIuE",
"JirZ_1F7uRs",
"RfKpZqaKn6s",
"qEbrbm02S68",
"78dig-cABbo",
"MoSg8SVm0w0",
"HNNsA8Mg8oc",
"yTNTxfJIPx0",
"0V-MxPv3dxc",
"1qrrvNVaFeA",
"LN6cQMvSHvQ",
"vpZKZLMvlz4",
"R5f_jJsVKLw",
"8XQE2_0CSZw",
"SCsFcaCUZjA",
"SJVyhb1tRso",
"nkhlKuz5SHw",
"SqvR9qLhabQ",
"MeAzjf8If48",
"YazSrl1zeBI",
"SB3tlwGZVsw",
"qPBSaX1pR0g",
"bsPWkSYxm_k",
"Cib-R18tQiE",
"AUr4GWLVNFg",
"iRA1w5VxtsM",
"9sbovwN4_Zw",
"FIcxJlkEi8o",
"M9kt5ZSjX_I",
"EkgwD4_RZnE",
"HXJyXSBqJSo",
"CoYNcY0Tp_4",
"zaJQn676M9g",
"RAQCxkt07L8",
"iCziACeridQ",
"iQaFDpiNOlA",
"clDgsheEb9g",
"O8Oh8uM-gLY",
"hRH9edUACcI",
"-AOGX_95yAQ",
"YPmqH-8kwek",
"rmDg3eVWT8E",
"KsvaR6yFLhI",
"NDwIpVZKfwU",
"_ZeJxtwiMnE",
"6ZMPsz2bjIY",
"8Frn76eH3aI",
"3Qzpj6UUxhE",
"17bnT1NHKbs",
"KhPcQqAgFL8",
"VqLhPgU74qE",
"Ay0yFRk77qs",
"CTYl99LH8_4",
"ojnWVGJRdCg",
"kP9gWdLu8YM",
"LOU9nXvriC0",
"DEeJ5nO6v3k",
"bX8OEmOlD2U",
"dD_67ZmfPTc",
"gleBvTNU6RM",
"ET8LoPsEnbE",
"D041h9adMOE",
"XWiSCgnuyQE",
"bvhi62gkXtU",
"NjLTwEPjllI",
"bP5K-pntO0k",
"A6qR7UhLvng",
"C_kwjJLepLg",
"ydwWWYItLcA",
"8Y93OJs7Sq8",
"cB9p5zd0eog",
"gBl2zWt1RB8",
"a3b_2VVmkPA",
"8GtCUqWTQh0",
"hhkZJ6tJq90",
"HwDRjt-_wmo",
"P6pRPCeQLD4",
"sqv8iaE_3_Q",
"JFYG1RRCkUw",
"mJgVOV9jRZU",
"irwvQ9XaFQI",
"RYXlHkqqdh8",
"qYENYgbIDzg",
"l1BhkFCqsRw",
"A6T65_3_Mn4",
"6UgZbs11fAU",
"FkswsIoQ-x4",
"HINKNjZlb7U",
"J2ifneIg3Zs",
"fTDuDxDLgME",
"WHFZ_PC3fMA",
"PVN59TyJ5-k",
"52H7Ugtu_xs",
"87iQxRiNTR0",
"xgitH-85LW0",
"V6E753Qw_yU",
"MGn3ISSKbY0",
"87WDy9Vrf_g",
"ey-D3isEYCc",
"ndaSrMS44KQ",
"oVPXRGG8lwU",
"Ajg6nkgmRK8",
"V4g-eU9np40",
"JX-SVLAVkG4",
"UTLbpDsdtQA",
"2MZdov79-e8",
"NA8wEvuexaY",
"Z3Z4OvtFX-Q",
"HoW4ivAHOvE",
"pMMUiyJ9p7o",
"h8oHehkCMdo",
"v6q1Ok2ctjA",
"6bImSBK6uWc",
"yYtL_9xNGC8",
"XK7n83car3g",
"dHOZaEoyXb4",
"9hEnANIvcGs",
"p9-LUcLsTLc",
"sQPWALYe77M",

"U-SpTfzZwFY",
"icZ5asGMBEY",

  ];

  const videoDescriptions = [
    " Information Theory Coding | Uncertainty, Properties of Information with Proofs | ITC Lectures;https",
" Solved Numerical on Information Content | Information Theory and coding Lectures in Hindi;https",
" Entropy Introduction | Properties with Proofs | Information Theory Coding(ITC) Lectures Hindi;https",
" Entropy Source Efficiency, Redundancy, Information Rate with Solved Problems | ITC Lectures;https",
" Shannon Fano Encoding Algorithm with Solved Problems | Information Theory Coding(ITC) Lectures;https",
" Ambiguity Problem in Shannon Fano Encoding Algorithm | Information Theory Coding(ITC) Lectures;https",
" Huffman Coding Algorithm with solved problems | Information Theory Coding(ITC) Lectures;https",
" Huffman Coding | Solved Problems on Ternary, Quaternary Coding | ITC Lectures Hindi;https",
" Lempel Zip Coding | Solved Problems | Information Theory Lectures(ITC Course) in Hindi;https",
" Communication Channel | Channel Matrix, Joint & Conditional Probability | ITC Lectures Hindi;https",
" Joint Probability Matrix | Properties | Information Theory and Coding Lectures(ITC Course);https",
" Mutual Information | Average Mutual Information | Properties | Solved Problems | ITC Course;https",
" Proofs of Mutual Information Properties | Information Theory Coding(ITC Course) Lectures;https",
" Markoff Statistical Model for Information Sources | Tree Diagram | Information Theory Coding;https",
" Binary Communication | Symmetric Channel, System Entropies | Equivocation, Condition Entropy;https",
" Noiseless, Deterministic, Symmetric Channels | Special Channels | Information Theory Coding;https",
" Binary Symmetric Channel(BSC) | Special Channels | Information Theory Coding Lectures Hindi;https",
" Binary Erasure Channel(BEC) | Special Channels | Information Theory Coding Lectures Hindi;https",
" Cascaded Channels | Special Channels | Information Theory Coding Lectures(ITC Course) Hindi;https",
" Error Control Coding | Block Codes | Introduction, Terms, Formulas | ITC Lectures in Hindi;https",
" Error Control Coding | Single Parity Check Codes | Block Codes | ITC Lectures in Hindi;https",
" Product Codes | Error Coding | Block Codes | Information Theory Coding(ITC) Full Course Hindi;https",
" Repetition Codes, Majority Vote Decoding with Example | Error Coding | ITC Lectures in Hindi;https",
" Linear Codes | Introduction, Properties | Error Control Coding | ITC Lectures in Hindi;https",
" Hamming Codes | Error Control Coding | Hamming Weight, Distance, Minimum Distance | ITC Hindi;https",
" Linear Codes Generator Matrix | Example to Generate Codewords | ITC Lectures in Hindi;https",
" Linear Codes Systematic Generator Matrix | Information Theory Coding(ITC Course) Lectures;https",
" Linear Codes Parity Check Matrices | Information Theory Coding(ITC Course) Lectures;https",
" Linear Codes Error Syndromes | Syndrome Table | Error Detection & Correction | ITC Lectures;https",
" Cyclic Codes, Polynomials Arithmetic with Examples | Information Theory Coding Lectures Hindi;https",
" Cyclic Codes Generator Polynomials | Systematic, Non-Systematic Coding Decoding | ITC Course;https",
" BCH Codes | Error Control Coding | Properties, Generator Polynomial, Example | ITC Lectures;https",
" Reed Solomon Codes | Error Control Coding | Properties, Advantages, Generator Polynomial | ITC;https",
" Convolutional Codes | Introduction, Code Rate, Constraint Length, Code Dimension | ITC Lectures;https",
" Convolutional Codes Encoder State | Code Tree | Information Theory Coding Lectures in Hindi;https",
" Convolutional Codes Code Trellis | State Diagram | Difference between Code Tree & Code Trellis;https",
" Viterbi Algorithm | Decoding Convolutional Code | Information theory coding lectures in Hindi;https",
"L41 | Huffman Coding | Lossless Compression Algorithm || Digital Image Processing (AKTU)",
"L42 | Shannon Fano Coding | Lossless Compression Algorithm || Digital Image Processing (AKTU)",
"Introduction to Signals and Systems",
"Continuous and Discrete Time Signals",
"Addition of Continuous-Time Signals",
"Multiplication of Continuous-Time Signals",
"Time Scaling of Continuous-Time Signals",
"Amplitude Scaling of Continuous-Time Signals",
"Time Shifting of Continuous-Time Signals",
"Amplitude Shifting of Continuous-Time Signals",
"Reversal of Continuous-Time Signals",
"Multiple Transformations of Continuous-Time Signals",
"Multiple Transformations of CTS (Important Point & Shortcut)",
"Multiple Transformations of CTS (Solved Problem 1)",
"Multiple Transformations of CTS (Solved Problem 2)",
"Even and Odd Signals",
"Even and Odd Components of a Signal",
"Properties of Even and Odd Signals",
"Even and Odd Signals (Solved Problem 1)",
"Even and Odd Signals (Solved Problem 2)",
"Even and Odd Signals (Solved Problem 3)",
"Even and Odd Signals (Solved Problem 4)",
"Periodic and Non-Periodic Signals",
"Periodic and Non-Periodic Signals (Important Point)",
"Calculation of Fundamental Period",
"Periodic and Non-Periodic Signals (Solved Problems)",
"Effect of Time-Shifting & Time-Scaling on Fundamental Time Period",
"Effect of Time-Reversal and Phase Shift on Fundamental Time Period",
"Effect of Amplitude-Shifting on Fundamental Time Period",
"Effect of Amplitude-Scaling on Fundamental Time Period",
"Effect of Amplitude Reversal on Fundamental Time Period",
"Conjugate Symmetric Signals",
"Conjugate Antisymmetric Signals",
"Half-Wave Symmetric Signals",
"Half Wave Symmetric Signals (Solved Problems)",
"Area of Continuous-Time Signals",
"Average Value of Continuous-Time Signals",
"Average Value of Continuous-Time Signals (Solved Problems) | Part 1",
"Average Value of Continuous-Time Signals (Solved Problems) | Part 2",
"Average Value of Continuous Time Signals (Solved Problems) | Part 3",
"Energy and Power of Continuous Time Signals",
"Energy Signals",
"Energy of CT Signals (Solved Problems) | Part 1",
"Energy of CT Signals (Solved Problems) | Part 2",
"Energy of CT Signals (Solved Problems) | Part 3",
"Power Signals",
"Power of CT Signals (Solved Problems) | Part 1",
"Power of CT Signals (Solved Problems) | Part 2",
"Power of CT Signals (Solved Problems) | Part 3",
"Power, RMS & Average Values of Standard Signals",
"Neither Energy Nor Power (NENP) Signals",
"Shortcut for Energy, Power & NENP Signals",
"Energy, Power & NENP Signals (Solved Problem 1)",
"Energy, Power & NENP Signals (Solved Problem 2)",
"Energy, Power & NENP Signals (Solved Problem 3)",
"Energy and Power of Discrete-Time Signals",
"Orthogonal Signals",
"Orthogonal Signals (Solved Problems 1)",
"Orthogonal Signals (Solved Problems 2)",
"Orthogonal Signals (Solved Problems 3)",
"Unit Impulse Signal",
"Properties of Impulse Signal (Part 1)",
"Properties of Impulse Signal (Part 2)",
"Impulse Signal (Solved Problems) | Part 1",
"Impulse Signal (Solved Problems) | Part 2",
"Unit Step Signal",
"Unit Ramp Signal",
"Unit Parabolic Signal",
"Relation between Unit Impulse and Unit Step Signals",
"Signum Function",
"Unit Rectangular Function",
"Unit Triangular Function",
"Sinc Function",
"Sampling Property of Unit Impulse Signal",
"Exponential Signals (Real and Complex)",
"Mathematical Representation of Signal Waveforms (Shortcut)",
"Mathematical Representation of Signal Waveforms (Solved Problems)",
"Differentiation of Continuous-Time Signals",
"Differentiation of Continuous Time Signals (Solved Problems)",
"Integration of Continuous-Time Signals",
"Integration of Continuous-Time Signals (Solved Problem)",
"Graphical Integration - Examples (Part 1)",
"Graphical Integration - Examples (Part 2)",
"Basic System Properties",
"Static and Dynamic Systems",
"Static and Dynamic Systems (Solved Problems) | Part 1",
"Static and Dynamic Systems (Solved Problems) | Part 2",
"Causal and Non-Causal Systems",
"Causal and Non-Causal Systems (Solved Problems) | Part 1",
"Causal and Non-Causal Systems (Solved Problems) | Part 2",
"Time-Invariant and Time-Variant Systems",
"Time-Invariant and Time-Variant Systems (Solved Problems) | Part 1",
"Time-Invariant and Time-Variant Systems (Solved Problems) | Part 2",
"Time-Invariant and Time-Variant Systems (Split System)",
"Linear and Non-Linear Systems",
"Linear and Non-Linear Systems (Solved Problems) | Part 1",
"Linear and Non-Linear Systems (Solved Problems) | Part 2",
"Linear and Non-Linear Systems (Solved Problems) | Part 3",
"Linear and Non-Linear Systems (Solved Problems) | Part 4",
"Linear and Non-Linear Systems (Integral & Differential Operators)",
"Linear and Non-Linear Systems (Even & Odd Operators)",
"Linear and Non-Linear Systems (Real & Imaginary Operators)",
"Linear and Non-Linear Systems (Various Nonlinear Operators)",
"Linear and Non-Linear Systems (All Properties)",
"Checking System Linearity using Transfer Characteristics",
"Invertible and Non-Invertible Systems",
"Invertible and Non-Invertible Systems (Solved Problems)",
"Stable and Unstable Systems",
"Stable and Unstable Systems (Solved Problems) | Part 1",
"Stable and Unstable Systems (Solved Problems) | Part 2",
"Prerequisites for LTI Systems (Revision of Linearity & Time Variance)",
"Prerequisites for LTI Systems (Laplace Transform)",
"Linear Time-Invariant (LTI) Systems",
"Transfer Function",
"Transfer Function Calculation",
"Impulse Response and Convolution",
"Introduction to Convolution Operation",
"Properties of Convolution (Part 1)",
"Properties of Convolution (Part 2)",
"Properties of Convolution (Part 3)",
"Properties of Convolution (Part 4)",
"Convolution Operation (Shortcut)",
"Convolution (Solved Problem 1)",
"Convolution (Solved Problem 2)",
"Convolution (Solved Problem 3)",
"Convolution (Solved Problem 4)",
"Convolution (Solved Problem 5)",
"Convolution (Solved Problem 6)",
"Static LTI System",
"Static LTI System (Solved Problems)",
"Causal LTI System",
"Causal LTI System (Solved Problems)",
"Stable LTI System",
"Stable LTI System (Solved Problems) | Part 1",
"Stable LTI System (Solved Problems) | Part 2",
"Harmonics and LTI System",
"Magnitude Distortion in LTI Systems",
"Phase Distortion in LTI Systems",
"Distortionless LTI System",
"Group Delay and Phase Delay",
"Group Delay & Phase Delay (Solved Problems)",
"Standard Differential Equation for LTI Systems",
"Introduction to Fourier Series",
"Conditions for Existence of Fourier Series (Dirichlet Conditions)",
"Trigonometric Fourier Series",
"Trigonometric Fourier Series (Example 1)",
"Trigonometric Fourier Series (Example 2)",
"Trigonometric Fourier Series (Example 3)",
"Trigonometric Fourier Series (Example 4)",
"Trigonometric Fourier Series (Example 5)",
"Complex Exponential Fourier Series",
"Complex Exponential Fourier Series (Example 1)",
"Complex Exponential Fourier Series (Example 2)",
"Complex Exponential Fourier Series (Example 3)",
"Complex Exponential Fourier Series (Example 4)",
"Complex Exponential Fourier Series (Example 5)",
"Relation between Fourier Coefficients",
"Relation between Fourier Coefficients (Solved Problem)",
"x(t)−Cn Pairs (Shortcut for Objectives)",
"Complex Exponential Fourier Series (Solved MCQ 1)",
"Complex Exponential Fourier Series (Solved MCQ 2)",
"Complex Exponential Fourier Series (Solved MCQ 3)",
"Symmetricities in Fourier Series (Part 1)",
"Symmetricities in Fourier Series (Part 2)",
"Hidden Symmetry in Fourier Series (Examples)",
"Properties of Fourier Series (Part 1)",
"Properties of Fourier Series (Part 2)",
"Properties of Fourier Series (Part 3)",
"Properties of Fourier Series (Part 4)",
"Properties of Fourier Series (Part 5)",
"Properties of Fourier Series (Part 6)",
"Parseval's Power Theorem",
"Parseval's Power Theorem (Solved Example)",
"Properties of Fourier Series (Solved Problems)",
"Fourier Series for LTI Systems",
"Introduction to Fourier Transform",
"Conditions for Existence of Fourier Transform (Dirichlet Conditions)",
"Properties of Fourier Transform (Part 1)",
"Properties of Fourier Transform (Part 2)",
"Properties of Fourier Transform (Part 3)",
"Properties of Fourier Transform (Part 4)",
"Properties of Fourier Transform (Part 5)",
"Properties of Fourier Transform (Part 6)",
"Properties of Fourier Transform (Part 7)",
"Properties of Fourier Transform (Part 8)",
"Parseval's Energy Theorem",
"Duality Property of Fourier Transform",
"Fourier Transform of Basic Signals (DC Value)",
"Fourier Transform of Basic Signals (Impulse Signal)",
"Fourier Transform of Basic Signals (Exponential Signals)",
"Fourier Transform of Basic Signals (Signum Function)",
"Fourier Transform of Basic Signals (Unit Step Signal)",
"Fourier Transform of sgn(t) & u(t) [Important Shortcut]",
"Fourier Transform of Basic Signals (Complex Exponential Signal)",
"Fourier Transform of Basic Signals (Cosω₀t)",
"Fourier Transform of Basic Signals (Sinω₀t)",
"Fourier Transform of Basic Signals (Rectangular Function)",
"Fourier Transform of Basic Signals (Triangular Function)",
"Fourier Transform of Basic Signals (Sampling Function)",
"Fourier Transform (Solved Problem 1)",
"Fourier Transform (Solved Problem 2)",
"Fourier Transform (Solved Problem 3)",
"Fourier Transform (Solved Problem 4)",
"Fourier Transform (Solved Problem 5)",
"Fourier Transform (Solved Problem 6)",
"Fourier Transform (Solved Problem 7)",
"Fourier Transform (Solved Problem 8)",
"Fourier Transform (Solved Problem 9)",
"Fourier Transform (Solved Problem 10)",
"Calculation of Cn using Fourier Transform",
"Fourier Transform for Periodic Signals",
"Fourier Transform (Solved Problem 11)",
"x(t)−X(ω) Pairs (Shortcut for Objectives)",
"Fourier Transform (Solved Problem 12)",
"Fourier Transform (Solved Problem 13)",
"Fourier Transform (Solved Problem 14)",
"Fourier Transform (Solved Problem 15)",
"Fourier Transform (Solved Problem 16)",
"Fourier Transform (Solved Problem 17)",
"Fourier Transform (Solved Problem 18)",
"Fourier Transform (Solved Problem 19)",
"Fourier Transform (Solved Problem 20)",
"Fourier Transform (Solved Problem 21)",
"Fourier Transform (Solved Problems 22 & 23)",
"Introduction to Laplace Transform",
"Relation between Laplace Transform & Fourier Transform",
"Condition for Existence of Laplace Transform",
"ROC and its Properties",
"ROC and Stability",
"Shortcut for Region of Convergence (ROC)",
"Properties of Laplace Transform (Part 1)",
"Properties of Laplace Transform (Part 2)",
"Properties of Laplace Transform (Part 3)",
"Properties of Laplace Transform (Part 4)",
"Properties of Laplace Transform (Part 5)",
"Properties of Laplace Transform (Part 6)",
"Initial Value Theorem",
"Final Value Theorem",
"Laplace Transform of Basic Signals (Unit Impulse Signal)",
"Laplace Transform of Basic Signals (Unit Step Signal)",
"Laplace Transform of Basic Signals (DC Value & Signum Function)",
"Laplace Transform of Basic Signals (Exponential Signals)",
"Laplace Transform of Basic Signals (Unit Ramp Signal)",
"Laplace Transform of Basic Signals [Cosω₀t.u(t)]",
"Laplace Transform of Basic Signals [Sinω₀t.u(t)]",
"Laplace Transform (Solved Problem 1)",
"Laplace Transform (Solved Problem 2)",
"Laplace Transform (Solved Problem 3)",
"Laplace Transform (Solved Problem 4)",
"Laplace Transform (Solved Problem 5)",
"Laplace Transform (Solved Problem 6)",
"Laplace Transform (Solved Problem 7)",
"Laplace Transform (Solved Problems 8 & 9)",
"Laplace Transform (Solved Problem 10)",
"Laplace Transform (Solved Problem 11)",
"Inverse Laplace Transform",
"Inverse Laplace Transform (Solved Problem)",
"ROC and Stability of Causal LTI Systems",
"Laplace Transform to Solve Differential Equations",
"Laplace Transform (Solved Problem 12)",
"Laplace Transform (Solved Problem 13)",
"Laplace Transform (Solved Problem 14)",
"Sampling Theorem",
"Nyquist Rate & Nyquist Interval",
"Properties of Nyquist Rate",
"Nyquist Rate (Solved Problem 1)",
"Nyquist Rate (Solved Problem 2)",
"Nyquist Rate (Solved Problem 3)",
"Reconstruction of Signals",
"Reconstruction of a Signal Using Practical LPF",
"Frequency Components Present in S(f)",
"Reconstruction of Signals (Solved Problem 2)",
"Reconstruction of Signals (Solved Problem 3)",
"Sampling Theorem for Band Pass Signals",
"Operations on Discrete Time Signals (Time Shifting)",
"Operations on DTS (Time Compression, Time Expansion & Time Reversal)",
"Operations on DTS (Amplitude Scaling & Amplitude Reversal)",
"Addition of Discrete Time Signals",
"Multiplication of Discrete Time Signals",
"Multiple Operations on Discrete Time Signals (Part 1)",
"Multiple Operations on Discrete Time Signals (Part 2)",
"Even and Odd Discrete Time Signals",
"Even and Odd Parts of Discrete Time Signal",
"Conjugate Symmetric and Conjugate Antisymmetric DTS",
"Periodic Discrete Time Signals",
"Periodic Discrete Time Signals (Solved Problems)",
"Discrete Time Energy Signals",
"Discrete Time Energy Signals (Solved Problems)",
"Discrete Time Power Signals",
"Discrete Time Power Signals (Solved Problems)",
"Unit Impulse Sequence",
"Unit Step & Unit Ramp Sequences",
"Discrete Time Signum Function",
"Discrete Time Convolution",
"Discrete Time Convolution (Tabular Method)",
"Static & Dynamic Discrete Time Systems",
"Causal and Non-Causal Discrete Time Systems",
"Time−Invariant & Time−Variant Discrete Time Systems",
"Linear and Non−Linear Discrete Time Systems",
"Stable & Unstable Discrete Time Systems",
"Discrete Time Signals & Systems (Solved Problem 1)",
"Discrete Time Signals & Systems (Solved Problem 2)",
"Discrete Time Signals & Systems (Solved Problem 3)",
"Discrete Time Signals & Systems (Solved Problem 4)",
"Discrete Time Signals & Systems (Solved Problem 5)",
"Discrete Time Signals & Systems (Solved Problem 6)",
"Introduction to Z-Transform",
"Condition for Existence of Z-Transform",
"Properties of Z-Transform (Part 1)",
"Properties of Z-Transform (Part 2)",
"Properties of Z-Transform (Part 3)",
"Properties of Z-Transform (Part 4)",
"Properties of Z-Transform (Part 5)",
"Properties of Z-Transform (Initial Value Theorem)",
"Properties of Z-Transform (Final Value Theorem)",
"Lect 01| Modulation | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 02 | Amplitude Modulation | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 03|Power calculation of AM| Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO |",
"Lect 04| Generation and Detection of AM| Communication System | Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 05| Hilbert transform| Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO |",
"Lect 06|Generation & Detection of SSB-SC|Communication System | By Saket Sir |EE/EC/IN|GATE/ESE/ISRO",
"Lect 07| Angle Modulation (part-1)| Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 08| Angle Modulation (part-2)| Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 09| Types of Angle Modulation | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 10| Generation of FM| Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 11| Random variable | CDF | PDF | Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 12| Mean and variance |Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 13| Error function | Gaussian RV |  Communication System | By Saket Sir |EE/EC/IN|GATE/ESE/ISRO",
"Lect 14| Central Limit Theorem | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 15| Random Process | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 16| Sampling | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 17| Questions on Sampling| Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 18| Quantization and SQNR | Communication System | By Saket Sir | EE/EC/IN | GATE/ESE/ISRO",
"Lect 19 | ISI and bandwidth | Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 20 | Practice Questions |Communication System |CRASH COURSE By Saket Sir |GATE/ESE/ISRO",
"Lect 21| DPCM and DM |Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 22| Disadvantages of DM and TDM|Communication System | By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 23 | Digital Modulation|Communication System |CRASH COURSE By Saket Sir|EE/EC/IN|GATE/ESE/ISRO",
"Lect 24 |Practice Question|Communication System |CRASH COURSE By Saket Sir| EE/EC/IN |GATE/ESE/ISRO",
"Lect 25 | Matched Filter |Communication System | CRASH COURSE By Saket Sir | EE/EC/IN |GATE/ESE/ISRO",
"Lect 26| Probability of error |Communication System|  CRASH COURSE By Saket Sir  |EC|GATE/ESE/ISRO",
"Lect 27 | Practice Questions|Communication System | CRASH COURSE By Saket Sir | EE/EC |GATE/ESE/ISRO",
"Lect 28 | Practice Questions|Communication System | CRASH COURSE By Saket Sir | EE/EC |GATE/ESE/ISRO",
"Lect 29 | Information Theory|Communication System | CRASH COURSE By Saket Sir | EE/EC |GATE/ESE/ISRO",
"Lect 30 | Conditional Entropy|Communication System | CRASH COURSE By Saket Sir |EE/EC|GATE/ESE/ISRO",
"Lect 31 | Linear block code|Communication System | Crash Course by Saket Verma Sir |EC| GATE 2021",


"SHANNON FANO CODING SOLVED EXAMPLE - with table and calculations - Hindi",
"HUFFMAN CODING SOLVED EXAMPLE in simple way| Electronics Subjectified | In hindi",


    "",
  ];

  const videoData = videoIDs.map((id, i) => ({
    id: i + 1,
    title: `PDC Video ${i + 1}`,
    thumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`,
    videoUrl: `https://www.youtube.com/embed/${id}`,
    description: videoDescriptions[i] || ""
  }));

  const [selectedVideo, setSelectedVideo] = useState(null);
  const [selectedSection, setSelectedSection] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const openVideo = (v) => setSelectedVideo(v);
  const closeVideo = () => setSelectedVideo(null);

  const renderSection = (key, title, start, end) => (
    <section id={key} className="mb-12">
      <h2 className="text-2xl font-bold mb-4">{title}</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
        {videoData.slice(start, end).map((video) => (
          <div
            key={video.id}
            onClick={() => openVideo(video)}
            className="bg-gray-800 rounded-lg shadow-lg cursor-pointer transform hover:scale-[1.02] transition duration-300 flex flex-row items-start p-3 sm:flex-col sm:p-4"
          >
            <div className="flex-shrink-0 w-2/5 sm:w-full">
              <img
                src={video.thumbnail}
                alt={video.title}
                className="w-full aspect-video object-cover rounded"
              />
            </div>
            <div className="flex-grow min-w-0 pl-3 sm:pl-0 sm:pt-3">
              <h3 className="text-sm sm:text-base font-semibold mb-1 line-clamp-2">
                {video.title}
              </h3>
              <p className="text-xs sm:text-sm text-gray-400 line-clamp-2">
                {video.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );

  return (
    <div className="flex bg-black text-white w-full min-h-screen">
      {/* SIDEBAR */}
      {sidebarOpen && (
        <aside className="fixed top-0 right-0 h-full w-60 bg-gray-900 border-l border-gray-700 p-4 overflow-y-auto z-40">
          <div className="flex items-center justify-between mb-6">
            <h1 className="text-xl font-bold leading-none">Sections</h1>
            <button
              onClick={() => setSidebarOpen(false)}
              className="text-white text-xl font-bold leading-none hover:text-red-500 transition"
            >
              ✖
            </button>
          </div>
          <nav className="space-y-4">
            {[
              ["All Videos", "All Videos", 0, 39],
              ["Neso", "Neso", 39, 352],
              ["Modulation,etc.", "Modulation,etc.", 352, 383],
              ["problems", "Problems", 383, 400],
            ].map(([key, label]) => (
              <button
                key={key}
                onClick={() => setSelectedSection(key)}
                className={`w-full text-left px-3 py-2 rounded transition-all duration-500 ${
                  selectedSection === key
                    ? 'bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text'
                    : 'text-white hover:bg-gradient-to-r hover:from-purple-400 hover:via-pink-500 hover:to-red-500 hover:bg-clip-text hover:text-transparent'
                }`}
              >
                {label}
              </button>
            ))}
          </nav>
        </aside>
      )}

      {/* CONTENT */}
      <main className={`flex-1 pt-4 p-4 sm:p-8 ${sidebarOpen ? 'pr-64' : ''}`}>        
        {/* HEADER WITH INLINE TOGGLE */}
        <div className="flex items-center justify-center mb-6 sm:mb-8 relative">
          <h1 className="text-3xl sm:text-4xl font-bold">Principles of Data Communication - Video Lectures</h1>
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="absolute right-0 text-3xl sm:text-4xl text-white hover:text-gray-300 transition"
          >
            {sidebarOpen ? '✖' : '⋮'}
          </button>
        </div>

        {selectedSection === null && renderSection("All Videos", "All Videos ", 0, 39)}
        {selectedSection === null && renderSection("Neso", "Neso ", 39, 352)}
        {selectedSection === null && renderSection("Modulation,etc.", "Modulation,etc. ", 352, 383)}
        {selectedSection === null && renderSection("problems", "Problem ", 383, 400)}

        {selectedSection === "All Videos" && renderSection("All Videos", "All Videos", 0, 39)}
        {selectedSection === "Neso" && renderSection("Neso", "Neso ", 39, 352)}
        {selectedSection === "Modulation,etc." && renderSection("Modulation,etc.", "Modulation,etc. ", 352, 383)}
        {selectedSection === "problems" && renderSection("problems", "Problem ", 383, 400)}
      </main>

      {/* VIDEO MODAL */}
      {selectedVideo && (
        <div className="fixed inset-0 bg-black bg-opacity-90 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-900 p-4 sm:p-6 rounded-lg w-full max-w-3xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4 gap-2">
              <h2 className="text-xl sm:text-2xl font-semibold truncate">
                {selectedVideo.title}
              </h2>
              <button
                onClick={closeVideo}
                className="text-white text-lg hover:text-red-500 transition flex-shrink-0"
              >
                ✖
              </button>
            </div>
            <div className="w-full aspect-video mb-4">
              <iframe
                className="w-full h-full rounded"
                src={selectedVideo.videoUrl}
                title={selectedVideo.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>
            <p className="text-gray-300 text-sm sm:text-base">
              {selectedVideo.description}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default PDC;
