import React, { useState } from "react";

const SAS = () => {
  const videoIDs = [
    "s8rsR_TStaA",
"H4hk6N5vC1Q",
"TmkTwJT79yc",
"jPCgU4ghB8Q",
"jnB-U5KBvN4",
"sTHbXeiAB_c",
"9Cd5nVCFfc0",
"dnrJlCD2MLc",
"BzAbZfT6RxQ",
"3mQr7rU4lnA",
"6O2oEQ2UwxY",
"zsJmqRY1uW0",
"TiC4P9WLzo8",
"c_YLkvk_ZXI",
"d0DbwTJUy5c",
"wH-R5ao8Wmg",
"bb_z42C-1-E",
"5fX9RfTTvqI",
"BBwgM_UNkFU",
"_f2vBo-ZDdI",
"Gj9pDC_OBQU",
"zkHs90fmVf4",
"4kEZQ9RtItk",
"A3Il3OyNoso",
"SfIQ6fLk6co",
"Q74dKFrpf_I",
"Ppblm9W51ac",
"D7AVHFA5JDQ",
"pXuloeCvcqM",
"O1HRtZmkI4E",
"Rm8vde7ly24",
"736ockPyw6k",
"T_pXdbHIWEg",
"Vw5Pj7RWyUU",
"Ws4ISTh3JgU",
"ZZRqf5jT3vs",
"OPqRzo4FLqI",
"f3feXJr2cLc",
"0Kmqp-XX_F0",
"b7lpVBTSVIU",
"1cRt9Duemew",
"2VXB7r0GKVE",
"okeuvau35mA",
"7ajS31nqD78",
"vG0Q7BNocmI",
"q6w4bf7hp_s",
"_tRMChRAqRc",
"S45i6YbfUuQ",
"X32LydcZS50",
"pa8BtYyZcrY",
"22yUGXQj1_U",
"g9cx7Jhx7oU",
"UbuLRKNTznw",
"QafVncdLd-g",
"3sGKZdVF58U",
"3FZ4c7YzioA",
"TNiS4lgcIzg",
"zoFUAC6BZUA",
"suFh1FTETRI",
"CWozCRh4Nno",
"yRjob1yPbpM",
"qckigAXWa7w",
"Vdqq8LUhGG8",
"tI7sEfdnYdE",
"e0EPWBACGiU",
"-_7kIAn82cI",
"SWt2PYiGgKQ",
"T_pGvvyjIkI",
"JNXTgrbTnGc",
"9JrC44OyIFE",
"9sd4DWragBg",
"sSU57kZhMSc",
"IFaliBPD1UY",
"uN1jdUaK0Ak",
"Ep4h3f-qySY",
"XMuSNiCO-TI",
"jPMxF_qYZdg",
"1fuRIm0Lx0Q",
"mNRcFn3KMPk",
"O5OXd_IDDRI",
"3_VERjf1sgs",
"npsZ2SBeVpA",
"xJHJbo3VnmY",
"0sRAMfPUQ58",
"CtmctzdKTcU",
"mqwUtn5cip8",
"0TzBSqENELM",
"A5SlTkKfUz0",
"LezLNMznZm4",
"BZq7j2b-7Lw",
"P4_iWrawCZs",
"emRV4juY17s",
"wOQDGvCLOs8",
"QcAY1oPozhw",
"mJSipEX5nWk",
"kAy5LHGPlRY",
"RljiuMPVoM8",
"fVsDHeBTjY0",
"b7Go0FCeJeU",
"kvBKZnQNtn8",
"2bqrG-bUcKU",
"7N6UYfUOIvM",
"bqN9kXL3dlc",
"tq353ew4gEw",
"zkF-v7kS5_o",
"ngJ2QWvMPbI",
"5QtIfoqLncQ",
"IdwpoS7YeJA",
"EIYYhwTP1jk",
"aaurfdKG-oE",
"Y8iFJVmSQIk",
"aEkDVqQDLH8",
"A1Fk-RHaSkQ",
"-oNqg6JH0eI",
"_HATc2zAhcY",
"mRJOYC73DnE",
"GIQPtGPS974",
"Cfw5EKbJHlk",
"80uvr_tdSI8",
"nHahox9pCg0",
"dSoXmaLsVYA",
"tKA38sAf8SE",
"fM3zqjci3SQ",
"rzV1iWmqtX0",
"-xUow-nafEQ",
"znkTOn0SfYU",
"sf7TNuuAIxU",
"u6dPdJjj8Kw",
"xdxHuw7Rs8k",
"ZlRqlwWioiE",
"795NrVrGXRQ",
"oP33taQEp4s",
"Ifq3K6p6RrA",
"hMeHr7zrHDs",
"mNYfiFTdsXo",
"b_VEKvST-lQ",
"9VzN_CohuNs",
"yZN_1tyOcOE",
"m9tASJ9DaTY",
"it6kiQuWdCo",
"9R3-0-Xg_Ro",
"blS_OImUJ-c",
"0d-xE2SvsSo",
"Ck6k1ulzgec",
"yVF_POXZBlw",
"srZyO_fJgp8",
"1GYU0i7zyUU",
"67HXJWd5ysQ",
"oXrbcRyXj84",
"on9FgztLyyk",
"w9ukTqSKFg0",
"xX6btp7Yn0I",
"cXZLjcx7Dsc",
"14B-3mU66Rg",
"1kvuy_t4lCM",
"0gRfPntQGqg",
"lAFGC3Q3Yk0",
"AmFHyKDqIsc",
"0nYkFji8y0E",
"2nSWjCkMGdo",
"714h9_5LPso",
"ijyVvwYE6H0",
"gX7UDbN5QE0",
"ED--r1lByl4",
"U7YwVMEHAVI",
"3OmFm-Qi7nE",
"j44UINh3JWY",
"7NKxAP-H6PE",
"gY6nUWuHfq8",
"ko65IqajDT8",
"UfeQ0OkXNj4",
"XR5g_f6dmSE",
"ZDCsLiC46S8",
"rCw-FVegWJA",
"UaUZsO-lckA",
"0USI-48ovJI",
"vshs9v83d0M",
"dWN0DzqlCZk",
"ihfm31HOYJ8",
"khmB0NoJWfA",
"t05C3pvLbsc",
"mGmPCLUZuGY",
"44-q1WwPvhc",
"IrKSx4mMK5M",
"9OK_i-n8gN8",
"uQkCar2SbVY",
"9_LaBHem4GI",
"WjOlJ2lPZOg",
"m8itztttxPE",
"blf9rfmxGvo",
"GCxCHP6QSNM",
"fDrChXcplcA",
"pAmqpID_36g",
"c9zCIPsH4R4",
"M10lkIuJmTs",
"8pwGRTnY0W0",
"2T_KpTGUcHo",
"IKJuvJGjADY",
"W1MW1dkE0ro",
"1A0grLVxY4w",
"0_kHkdgzsxM",
"6nVvbSuyNaU",
"Lf8v1kg37YY",
"lBiW4gEZNfQ",
"yBjWlHQFruM",
"YzsbxApfE60",
"RemTOQX4tsU",
"2oJzdf63LgQ",
"9I4z5JPbvgg",
"rPr6lozpfPE",
"rYKb_V0Or7A",
"DkhMTj-YEpA",
"xAPv826E_Go",
"tD2kXTJ25dA",
"qE-WNoeMNvs",
"UMG0n3DItPg",
"KjzBW4POLBE",
"24Sm_x8UZLo",
"R83RrZCjvKo",
"S-B0r5D6fHI",
"OXC95lauAjk",
"xNx2NCeISas",
"1wWiA0l2GQk",
"S7zGQWX3FZQ",
"06DQVFZtfGw",
"LyOQVvPVIuE",
"JirZ_1F7uRs",
"RfKpZqaKn6s",
"qEbrbm02S68",
"78dig-cABbo",
"MoSg8SVm0w0",
"HNNsA8Mg8oc",
"yTNTxfJIPx0",
"0V-MxPv3dxc",
"1qrrvNVaFeA",
"LN6cQMvSHvQ",
"vpZKZLMvlz4",
"R5f_jJsVKLw",
"8XQE2_0CSZw",
"SCsFcaCUZjA",
"SJVyhb1tRso",
"nkhlKuz5SHw",
"SqvR9qLhabQ",
"MeAzjf8If48",
"YazSrl1zeBI",
"SB3tlwGZVsw",
"qPBSaX1pR0g",
"bsPWkSYxm_k",
"Cib-R18tQiE",
"AUr4GWLVNFg",
"iRA1w5VxtsM",
"9sbovwN4_Zw",
"FIcxJlkEi8o",
"M9kt5ZSjX_I",
"EkgwD4_RZnE",
"HXJyXSBqJSo",
"CoYNcY0Tp_4",
"zaJQn676M9g",
"RAQCxkt07L8",
"iCziACeridQ",
"iQaFDpiNOlA",
"clDgsheEb9g",
"O8Oh8uM-gLY",
"hRH9edUACcI",
"-AOGX_95yAQ",
"YPmqH-8kwek",
"rmDg3eVWT8E",
"KsvaR6yFLhI",
"NDwIpVZKfwU",
"_ZeJxtwiMnE",
"6ZMPsz2bjIY",
"8Frn76eH3aI",
"3Qzpj6UUxhE",
"17bnT1NHKbs",
"KhPcQqAgFL8",
"VqLhPgU74qE",
"Ay0yFRk77qs",
"CTYl99LH8_4",
"ojnWVGJRdCg",
"kP9gWdLu8YM",
"LOU9nXvriC0",
"DEeJ5nO6v3k",
"bX8OEmOlD2U",
"dD_67ZmfPTc",
"gleBvTNU6RM",
"ET8LoPsEnbE",
"D041h9adMOE",
"XWiSCgnuyQE",
"bvhi62gkXtU",
"NjLTwEPjllI",
"bP5K-pntO0k",
"A6qR7UhLvng",
"C_kwjJLepLg",
"ydwWWYItLcA",
"8Y93OJs7Sq8",
"cB9p5zd0eog",
"gBl2zWt1RB8",
"a3b_2VVmkPA",
"8GtCUqWTQh0",
"hhkZJ6tJq90",
"HwDRjt-_wmo",
"P6pRPCeQLD4",
"sqv8iaE_3_Q",
"JFYG1RRCkUw",
"mJgVOV9jRZU",
"irwvQ9XaFQI",
"RYXlHkqqdh8",
"qYENYgbIDzg",
"l1BhkFCqsRw",
"A6T65_3_Mn4",
"6UgZbs11fAU",
"FkswsIoQ-x4",
"HINKNjZlb7U",
"Vf9661S6dT4",
"rNMnHCYiQso",
"P8XCbtOseoI",
"nx9x5VjVyjM",
"8V8qkJwa_nM",
"dBN6rMEpKiI",
"xrBqDjktFOQ",
"CzSd4IZE5MY",
"jOw68i-CbXw",
"rPZ0LwksUkI",
"wFk9sFVPajo",
"MbdIgirvbHs",
"geG8nkJn9NM",
"pxJH96CBsFU",
"krsO_FZ7mSk",
"D8ojzlGXSUo",
"xRx7ODepf6k",
"8PfHejrZyaU",
"9VHPbOmxc0g",
"-BzJKYDlb9Y",
"dlQy2htuUjk",
"eINvF19tJyE",
"iV0lfjMtHpc",
"AhMKxC4Es_E",
"wJzI8TbUZxQ",
"xMqhHPPtZd4",
"sAx0cP0lAT4",
"LLzPuu_zAEI",
"gh9C95blTGE",
"_0a5Me1UQ5Y",
"2GZH6OU2-PU",
"XYeEBzkh2hU",
"nUirop9dbMs",
"UqPm4kzna_E",
"DK_Xmue8f90",
"PYJh-1TYhLw",
"DrUejLtXIRo",
"WbebNTFCsCc",
"B_8d_kLrGXw",
"EfYseHONbw8",
"iamHrLnHDeA",
"4fygMTVxUkI",
"hqw7-11mk9c",
"I2L5uIYRpvw",
"ftEPB0XqPzQ",
"szxUbsFsJmc",
"uR3mWTBw4sU",
"nApX3deHAPU",
"rYi4s-TTthI",
"JQ0-tjdmDJE",
"UUH1Qz2RhHc",
"9vDDZWXGTFc",
"0_U18SoAxP8",
"Yhsgd9bgfnA",
"wgXG186dYRs",
"_J_3-aLCz8E",
"icMBmXWG8vA",
"PwznvoXGsa8",
"rN_qwt4s6Fo",
"koJ4-KNZuZE",
"_rpsHQrKzF0",
"3Ww8lgF2eDw",
"zrZiYHpSi6E",
"Q8Jn6mVqGMA",
"PbPpyTdIrsQ",
"yeor8ShWdB4",
"ljDtxS4QSRg",
"m7WuwTPdnwc",
"hBXIF4P00SA",
"jATfsnpEbS0",
"0ZyyPyl5-OY",
"33tP4aqaliA",
"-Va6gy84buk",
"H2qrBp7PYE4",
"fXV7yW9qDaI",
"dP10vLm3hNM",
"H6JQJ6SPKhk",
"W149wDkynJk",
"cgD2Q64D9C0",
"w2IOWg0k47Y",
"cOUpR62hrLU",
"yVL5AsCflqo",
"oD_mz87mScc",
"HECZqdMQEvE",
"OBwRXy6K780",
"4NswD9w1_zM",
"4BBHBwUf4rM",
"pWXZTJkrjFY",
"oCPfKwfKgZs",
"qLKxRFq28YM",
"tqFjc1r1BQ0",
"C8xL5DYtI_0",
"TMAKfHfclic",
"n_atkx7pIZE",
"racJb1k1jas",
"aZziHAojWfE",
"Tgz-mxCYW1s",
"canQHe7EHLk",
"tSqRqlgCx-Q",
"fxGFSmSISmc",
"C1UaRN3YrWY",
"lqEw3Srdc6s",
"EHIuFF8wnCg",
"jjILCM8Swok",
"Xx2PHuIb6yo",
"MUqwIUnyTiw",
"f-om0DyrXP0",
"lnC7JZdGen4",
"gkXDR2ZudVw",
"XtW5pKfUUtc",
"_ZQV1y4k3EU",
"RQU5eJO9JSI",
"ad_960G7-Ro",
"vqxkMpPXOd0",
"iDoCbveIWaE",
"AJTihYt8hLk",
"XcOwSFt7t78",
"GfNKkoDcuhE",
"YF01qWgiPyg",
"yU0Rmx8wJHs",
"94SzhT3yKgE",
"8_gD-NESC78",
"n6mmRejN45o",
"1hudeqzvmnw",
"Lb1xWREdX58",
"PmQrqnqsTX4",
"zJAYY7j3rHE",
"IYT3Kri4G9M",
"-AG4DmHNJI0",
"sJT5mw8cKls",
"VsPCm48zbLI",
"YJU_OYa_Nfw",
"xFDKuBo1RJ0",
"E_dZyzmOqGg",
"SLWZ2bDtvkI",
"90LXNf8EFnk",
"ClQRQRsAuig",
"d_f28I-AQ1s",
"wtInpYzDc8k",
"deS6Q9m4kiM",
"CeZtHBBt0vs",
"lgB3i9AykJg",
"sfS6CRMB0tM",
"TmzPbZXmPao",
"152JzIbYnYU",
"KR4fC0XPUYQ",
"RwlIApjSZlo",
"tzJRNo_lEXY",
"sqkhPlunToU",
"neAZnrEa04I",
"Wucsmnfj1XY",
"l7_gSdwopjg",
"0bLZgO_1unQ",
"9KuOT0FAg8o",
"Aanqnw1QhQI",
"gTn4nAHRySQ",
"7EzjL6PTAT8",
"H9VGYOtaALA",
"MI8bpuDCkMg",
"_c1v-Tn6Qh8",
"DUNffm0G8N0",
"q3vsJkagenw",
"DfVm1EXe2wA",
"IQjqYmXFW6s",
"ak-jNfZNo4M",
"xSyMrsjZTxo",
"qIfD7bnOH4s",
"bsxQ36r_1yM",
"g5KsOqZDfu8",
"qSHdkVB0nnc",
"VmgaRXjlklw",
"_qpK8Jz2I-A",
"EnLk6WJdb28",
"R_pw9yErkOg",
"twR3A1N0Erg",
"G0qBobK-8R4",
"qjjbAVcr8t8",
"9gYAMippXEg",
"9ZJ73L7vwlY",
"6gjMV4ejBOg",
"I-cejdnY6Wc",
"yvP7RNA2M7c",
"5OObHrHo1Dg",
"WtyH_ShNC38",
"v4WTb9eoBnw",
"E08xrlN_jLY",
"60THpVtYor0",
"BEyw1p6u1xc",
"-0b7kB7l4Es",
"SDZAZWlWNVg",
"f8JHX9oktRw",
"iiWS3vn4vzM",
"sLNBu_IF-6M",
"GMi2dIfwk0Y",
"eohXpULsBiI",
"9AOLFdthcOI",
"aLRawXv-bic",
"DLPysr3IpzA",
"sTyxatzNo3w",
"MGhSaJYNrqM",
"gTZH9YExABA",
"YyQ9u6XzuiA",
"mXf5UmRW09c",
"2hhqIOwOLTw",
"Jk09ZFI28KA",
"PsK2iOcyu6M",
"ySaaDB8iBtw",
"XUzdeb6Vy88",
"cMAG6rhL3DI",
"x0l9DOJ6Hwg",
"I2zQ3d524P0",
"3OlWxjw-lpo",

  ];

  const videoDescriptions = [
    "Introduction to Signals and Systems",
    "Continuous and Discrete Time Signals",
    "Addition of Continuous-Time Signals",
    "Multiplication of Continuous-Time Signals",
    "Time Scaling of Continuous-Time Signals",
    "Amplitude Scaling of Continuous-Time Signals",
    "Time Shifting of Continuous-Time Signals",
    "Amplitude Shifting of Continuous-Time Signals",
    "Reversal of Continuous-Time Signals",
    "Multiple Transformations of Continuous-Time Signals",
    "Multiple Transformations of CTS (Important Point & Shortcut)",
    "Multiple Transformations of CTS (Solved Problem 1)",
    "Multiple Transformations of CTS (Solved Problem 2)",
    "Even and Odd Signals",
    "Even and Odd Components of a Signal",
    "Properties of Even and Odd Signals",
    "Even and Odd Signals (Solved Problem 1)",
    "Even and Odd Signals (Solved Problem 2)",
    "Even and Odd Signals (Solved Problem 3)",
    "Even and Odd Signals (Solved Problem 4)",
    "Periodic and Non-Periodic Signals",
    "Periodic and Non-Periodic Signals (Important Point)",
    "Calculation of Fundamental Period",
    "Periodic and Non-Periodic Signals (Solved Problems)",
    "Effect of Time-Shifting & Time-Scaling on Fundamental Time Period",
    "Effect of Time-Reversal and Phase Shift on Fundamental Time Period",
    "Effect of Amplitude-Shifting on Fundamental Time Period",
    "Effect of Amplitude-Scaling on Fundamental Time Period",
    "Effect of Amplitude Reversal on Fundamental Time Period",
    "Conjugate Symmetric Signals",
    "Conjugate Antisymmetric Signals",
    "Half-Wave Symmetric Signals",
    "Half Wave Symmetric Signals (Solved Problems)",
    "Area of Continuous-Time Signals",
    "Average Value of Continuous-Time Signals",
    "Average Value of Continuous-Time Signals (Solved Problems) | Part 1",
    "Average Value of Continuous-Time Signals (Solved Problems) | Part 2",
    "Average Value of Continuous Time Signals (Solved Problems) | Part 3",
    "Energy and Power of Continuous Time Signals",
    "Energy Signals",
    "Energy of CT Signals (Solved Problems) | Part 1",
    "Energy of CT Signals (Solved Problems) | Part 2",
    "Energy of CT Signals (Solved Problems) | Part 3",
    "Power Signals",
    "Power of CT Signals (Solved Problems) | Part 1",
    "Power of CT Signals (Solved Problems) | Part 2",
    "Power of CT Signals (Solved Problems) | Part 3",
    "Power, RMS & Average Values of Standard Signals",
    "Neither Energy Nor Power (NENP) Signals",
    "Shortcut for Energy, Power & NENP Signals",
    "Energy, Power & NENP Signals (Solved Problem 1)",
    "Energy, Power & NENP Signals (Solved Problem 2)",
    "Energy, Power & NENP Signals (Solved Problem 3)",
    "Energy and Power of Discrete-Time Signals",
    "Orthogonal Signals",
    "Orthogonal Signals (Solved Problems 1)",
    "Orthogonal Signals (Solved Problems 2)",
    "Orthogonal Signals (Solved Problems 3)",
    "Unit Impulse Signal",
    "Properties of Impulse Signal (Part 1)",
    "Properties of Impulse Signal (Part 2)",
    "Impulse Signal (Solved Problems) | Part 1",
    "Impulse Signal (Solved Problems) | Part 2",
    "Unit Step Signal",
    "Unit Ramp Signal",
    "Unit Parabolic Signal",
    "Relation between Unit Impulse and Unit Step Signals",
    "Signum Function",
    "Unit Rectangular Function",
    "Unit Triangular Function",
    "Sinc Function",
    "Sampling Property of Unit Impulse Signal",
    "Exponential Signals (Real and Complex)",
    "Mathematical Representation of Signal Waveforms (Shortcut)",
    "Mathematical Representation of Signal Waveforms (Solved Problems)",
    "Differentiation of Continuous-Time Signals",
    "Differentiation of Continuous Time Signals (Solved Problems)",
    "Integration of Continuous-Time Signals",
    "Integration of Continuous-Time Signals (Solved Problem)",
    "Graphical Integration - Examples (Part 1)",
    "Graphical Integration - Examples (Part 2)",
    "Basic System Properties",
    "Static and Dynamic Systems",
    "Static and Dynamic Systems (Solved Problems) | Part 1",
    "Static and Dynamic Systems (Solved Problems) | Part 2",
    "Causal and Non-Causal Systems",
    "Causal and Non-Causal Systems (Solved Problems) | Part 1",
    "Causal and Non-Causal Systems (Solved Problems) | Part 2",
    "Time-Invariant and Time-Variant Systems",
    "Time-Invariant and Time-Variant Systems (Solved Problems) | Part 1",
    "Time-Invariant and Time-Variant Systems (Solved Problems) | Part 2",
    "Time-Invariant and Time-Variant Systems (Split System)",
    "Linear and Non-Linear Systems",
    "Linear and Non-Linear Systems (Solved Problems) | Part 1",
    "Linear and Non-Linear Systems (Solved Problems) | Part 2",
    "Linear and Non-Linear Systems (Solved Problems) | Part 3",
    "Linear and Non-Linear Systems (Solved Problems) | Part 4",
    "Linear and Non-Linear Systems (Integral & Differential Operators)",
    "Linear and Non-Linear Systems (Even & Odd Operators)",
    "Linear and Non-Linear Systems (Real & Imaginary Operators)",
    "Linear and Non-Linear Systems (Various Nonlinear Operators)",
    "Linear and Non-Linear Systems (All Properties)",
    "Checking System Linearity using Transfer Characteristics",
    "Invertible and Non-Invertible Systems",
    "Invertible and Non-Invertible Systems (Solved Problems)",
    "Stable and Unstable Systems",
    "Stable and Unstable Systems (Solved Problems) | Part 1",
    "Stable and Unstable Systems (Solved Problems) | Part 2",
    "Prerequisites for LTI Systems (Revision of Linearity & Time Variance)",
    "Prerequisites for LTI Systems (Laplace Transform)",
    "Linear Time-Invariant (LTI) Systems",
    "Transfer Function",
    "Transfer Function Calculation",
    "Impulse Response and Convolution",
    "Introduction to Convolution Operation",
    "Properties of Convolution (Part 1)",
    "Properties of Convolution (Part 2)",
    "Properties of Convolution (Part 3)",
    "Properties of Convolution (Part 4)",
    "Convolution Operation (Shortcut)",
    "Convolution (Solved Problem 1)",
    "Convolution (Solved Problem 2)",
    "Convolution (Solved Problem 3)",
    "Convolution (Solved Problem 4)",
    "Convolution (Solved Problem 5)",
    "Convolution (Solved Problem 6)",
    "Static LTI System",
    "Static LTI System (Solved Problems)",
    "Causal LTI System",
    "Causal LTI System (Solved Problems)",
    "Stable LTI System",
    "Stable LTI System (Solved Problems) | Part 1",
    "Stable LTI System (Solved Problems) | Part 2",
    "Harmonics and LTI System",
    "Magnitude Distortion in LTI Systems",
    "Phase Distortion in LTI Systems",
    "Distortionless LTI System",
    "Group Delay and Phase Delay",
    "Group Delay & Phase Delay (Solved Problems)",
    "Standard Differential Equation for LTI Systems",
    "Introduction to Fourier Series",
    "Conditions for Existence of Fourier Series (Dirichlet Conditions)",
    "Trigonometric Fourier Series",
    "Trigonometric Fourier Series (Example 1)",
    "Trigonometric Fourier Series (Example 2)",
    "Trigonometric Fourier Series (Example 3)",
    "Trigonometric Fourier Series (Example 4)",
    "Trigonometric Fourier Series (Example 5)",
    "Complex Exponential Fourier Series",
    "Complex Exponential Fourier Series (Example 1)",
    "Complex Exponential Fourier Series (Example 2)",
    "Complex Exponential Fourier Series (Example 3)",
    "Complex Exponential Fourier Series (Example 4)",
    "Complex Exponential Fourier Series (Example 5)",
    "Relation between Fourier Coefficients",
    "Relation between Fourier Coefficients (Solved Problem)",
    "x(t)−Cn Pairs (Shortcut for Objectives)",
    "Complex Exponential Fourier Series (Solved MCQ 1)",
    "Complex Exponential Fourier Series (Solved MCQ 2)",
    "Complex Exponential Fourier Series (Solved MCQ 3)",
    "Symmetricities in Fourier Series (Part 1)",
    "Symmetricities in Fourier Series (Part 2)",
    "Hidden Symmetry in Fourier Series (Examples)",
    "Properties of Fourier Series (Part 1)",
    "Properties of Fourier Series (Part 2)",
    "Properties of Fourier Series (Part 3)",
    "Properties of Fourier Series (Part 4)",
    "Properties of Fourier Series (Part 5)",
    "Properties of Fourier Series (Part 6)",
    "Parseval's Power Theorem",
    "Parseval's Power Theorem (Solved Example)",
    "Properties of Fourier Series (Solved Problems)",
    "Fourier Series for LTI Systems",
    "Introduction to Fourier Transform",
    "Conditions for Existence of Fourier Transform (Dirichlet Conditions)",
    "Properties of Fourier Transform (Part 1)",
    "Properties of Fourier Transform (Part 2)",
    "Properties of Fourier Transform (Part 3)",
    "Properties of Fourier Transform (Part 4)",
    "Properties of Fourier Transform (Part 5)",
    "Properties of Fourier Transform (Part 6)",
    "Properties of Fourier Transform (Part 7)",
    "Properties of Fourier Transform (Part 8)",
    "Parseval's Energy Theorem",
    "Duality Property of Fourier Transform",
    "Fourier Transform of Basic Signals (DC Value)",
    "Fourier Transform of Basic Signals (Impulse Signal)",
    "Fourier Transform of Basic Signals (Exponential Signals)",
    "Fourier Transform of Basic Signals (Signum Function)",
    "Fourier Transform of Basic Signals (Unit Step Signal)",
    "Fourier Transform of sgn(t) & u(t) [Important Shortcut]",
    "Fourier Transform of Basic Signals (Complex Exponential Signal)",
    "Fourier Transform of Basic Signals (Cosω₀t)",
    "Fourier Transform of Basic Signals (Sinω₀t)",
    "Fourier Transform of Basic Signals (Rectangular Function)",
    "Fourier Transform of Basic Signals (Triangular Function)",
    "Fourier Transform of Basic Signals (Sampling Function)",
    "Fourier Transform (Solved Problem 1)",
    "Fourier Transform (Solved Problem 2)",
    "Fourier Transform (Solved Problem 3)",
    "Fourier Transform (Solved Problem 4)",
    "Fourier Transform (Solved Problem 5)",
    "Fourier Transform (Solved Problem 6)",
    "Fourier Transform (Solved Problem 7)",
    "Fourier Transform (Solved Problem 8)",
    "Fourier Transform (Solved Problem 9)",
    "Fourier Transform (Solved Problem 10)",
    "Calculation of Cn using Fourier Transform",
    "Fourier Transform for Periodic Signals",
    "Fourier Transform (Solved Problem 11)",
    "x(t)−X(ω) Pairs (Shortcut for Objectives)",
    "Fourier Transform (Solved Problem 12)",
    "Fourier Transform (Solved Problem 13)",
    "Fourier Transform (Solved Problem 313)",
    "Fourier Transform (Solved Problem 15)",
    "Fourier Transform (Solved Problem 16)",
    "Fourier Transform (Solved Problem 17)",
    "Fourier Transform (Solved Problem 18)",
    "Fourier Transform (Solved Problem 19)",
    "Fourier Transform (Solved Problem 20)",
    "Fourier Transform (Solved Problem 21)",
    "Fourier Transform (Solved Problems 22 & 23)",
    "Introduction to Laplace Transform",
    "Relation between Laplace Transform & Fourier Transform",
    "Condition for Existence of Laplace Transform",
    "ROC and its Properties",
    "ROC and Stability",
    "Shortcut for Region of Convergence (ROC)",
    "Properties of Laplace Transform (Part 1)",
    "Properties of Laplace Transform (Part 2)",
    "Properties of Laplace Transform (Part 3)",
    "Properties of Laplace Transform (Part 4)",
    "Properties of Laplace Transform (Part 5)",
    "Properties of Laplace Transform (Part 6)",
    "Initial Value Theorem",
    "Final Value Theorem",
    "Laplace Transform of Basic Signals (Unit Impulse Signal)",
    "Laplace Transform of Basic Signals (Unit Step Signal)",
    "Laplace Transform of Basic Signals (DC Value & Signum Function)",
    "Laplace Transform of Basic Signals (Exponential Signals)",
    "Laplace Transform of Basic Signals (Unit Ramp Signal)",
    "Laplace Transform of Basic Signals [Cosω₀t.u(t)]",
    "Laplace Transform of Basic Signals [Sinω₀t.u(t)]",
    "Laplace Transform (Solved Problem 1)",
    "Laplace Transform (Solved Problem 2)",
    "Laplace Transform (Solved Problem 3)",
    "Laplace Transform (Solved Problem 4)",
    "Laplace Transform (Solved Problem 5)",
    "Laplace Transform (Solved Problem 6)",
    "Laplace Transform (Solved Problem 7)",
    "Laplace Transform (Solved Problems 8 & 9)",
    "Laplace Transform (Solved Problem 10)",
    "Laplace Transform (Solved Problem 11)",
    "Inverse Laplace Transform",
    "Inverse Laplace Transform (Solved Problem)",
    "ROC and Stability of Causal LTI Systems",
    "Laplace Transform to Solve Differential Equations",
    "Laplace Transform (Solved Problem 12)",
    "Laplace Transform (Solved Problem 13)",
    "Laplace Transform (Solved Problem 313)",
    "Sampling Theorem",
    "Nyquist Rate & Nyquist Interval",
    "Properties of Nyquist Rate",
    "Nyquist Rate (Solved Problem 1)",
    "Nyquist Rate (Solved Problem 2)",
    "Nyquist Rate (Solved Problem 3)",
    "Reconstruction of Signals",
    "Reconstruction of a Signal Using Practical LPF",
    "Frequency Components Present in S(f)",
    "Reconstruction of Signals (Solved Problem 2)",
    "Reconstruction of Signals (Solved Problem 3)",
    "Sampling Theorem for Band Pass Signals",
    "Operations on Discrete Time Signals (Time Shifting)",
    "Operations on DTS (Time Compression, Time Expansion & Time Reversal)",
    "Operations on DTS (Amplitude Scaling & Amplitude Reversal)",
    "Addition of Discrete Time Signals",
    "Multiplication of Discrete Time Signals",
    "Multiple Operations on Discrete Time Signals (Part 1)",
    "Multiple Operations on Discrete Time Signals (Part 2)",
    "Even and Odd Discrete Time Signals",
    "Even and Odd Parts of Discrete Time Signal",
    "Conjugate Symmetric and Conjugate Antisymmetric DTS",
    "Periodic Discrete Time Signals",
    "Periodic Discrete Time Signals (Solved Problems)",
    "Discrete Time Energy Signals",
    "Discrete Time Energy Signals (Solved Problems)",
    "Discrete Time Power Signals",
    "Discrete Time Power Signals (Solved Problems)",
    "Unit Impulse Sequence",
    "Unit Step & Unit Ramp Sequences",
    "Discrete Time Signum Function",
    "Discrete Time Convolution",
    "Discrete Time Convolution (Tabular Method)",
    "Static & Dynamic Discrete Time Systems",
    "Causal and Non-Causal Discrete Time Systems",
    "Time−Invariant & Time−Variant Discrete Time Systems",
    "Linear and Non−Linear Discrete Time Systems",
    "Stable & Unstable Discrete Time Systems",
    "Discrete Time Signals & Systems (Solved Problem 1)",
    "Discrete Time Signals & Systems (Solved Problem 2)",
    "Discrete Time Signals & Systems (Solved Problem 3)",
    "Discrete Time Signals & Systems (Solved Problem 4)",
    "Discrete Time Signals & Systems (Solved Problem 5)",
    "Discrete Time Signals & Systems (Solved Problem 6)",
    "Introduction to Z-Transform",
    "Condition for Existence of Z-Transform",
    "Properties of Z-Transform (Part 1)",
    "Properties of Z-Transform (Part 2)",
    "Properties of Z-Transform (Part 3)",
    "Properties of Z-Transform (Part 4)",
    "Properties of Z-Transform (Part 5)",
    "Properties of Z-Transform (Initial Value Theorem)",
    "Properties of Z-Transform (Final Value Theorem)",
    "Signals and Systems by Engineering Funda",
    "Signals & Systems Trailer",
    "Introduction to Signals Explained: Basics, Examples, Representation, and Applications",
    "Classifications of Signals Explained: Continuous/Discrete, Even/Odd, Periodic/Aperiodic, Energy/Powe",
    "Standard Signals Explained: Impulse, Step, Ramp, Parabolic, Signum, Rectangular, Sinc & Sampling",
    "Operations on Signal Explained: Time Shifting, Time Folding, Time Scaling & Arithmetic Operations",
    "Operations on Signal Solved Examples: Time Shifting, Time Folding, Time Scaling & Arithmetic",
    "Plot Signal from given Function Solved Examples: Steps, Process, and Solutions",
    "Even and Odd Components of Signal Solved Examples: Steps, Process, and Solutions",
    "Periodicity of Signals Basics and Solved Examples",
    "Energy and Power of Signal from Waveforms Explained: Basics and Solved Examples",
    "Energy and Power of Step & Exponential Signal Solved Examples",
    "Energy and Power of Discrete Signal: Basics and Solved Examples",
    "Energy and Power Signals Solved Examples: Steps, Process, and Solutions",
    "Energy of Time Scaled Signal & Energy Verification by Parseval' Theorem: Solved Examples",
    "Introduction to Systems Explained: Basics, Elements, Examples, Types, and Applications",
    "Classifications of Systems: Linearity, Time Variant, Causality, Stability, and Invertibility",
    "Linear and Non Linear System Solved Examples: Basics, Steps, Calculations, and Solutions",
    "Time Invariant and Time Variant Systems Solved Examples: Basics, Steps, Calculations, and Solutions",
    "LTI and LTV Systems Solved Examples: Basics, Steps, Calculations, and Solutions",
    "Static and Dynamic Systems Solved Examples: Basics, Steps, Calculations, and Solutions",
    "Causal and Non-Causal Systems Solved Examples: Basics, Steps, Calculations, and Solutions",
    "Invertible and Non-Invertible Systems Explained: Basics, Differences, Applications, and Examples",
    "Stable and Unstable Systems Solved Examples: Basics, Steps, Calculations, and Solutions",
    "Impulse Response of Systems Explained: Basics, Parameters, and Solved Examples",
    "Convolution Explained: Basics, Formulas, Properties, and Examples",
    "Limits of Convolution & Area of Convoluted Signal Solved Examples",
    "Convolution of Continuous Time Signals Solved Example",
    "Convolution by Slide and Shift Method Solved Examples",
    "Convolution by Image Method Solved Example",
    "Convolution Solved Examples: Properties, Basics, and Step by Step Guide",
    "Area of Convoluted Signal Solved Example",
    "Linear Convolution of Discrete Signals Solved Examples",
    "Circular Convolution of Discrete Signals Solved Examples",
    "Circular Convolution by Matrix Method Solved Examples",
    "Deconvolution Solved Examples: Long Division Method and Conventional Method",
    "Laplace Transform Explained: Basics, System Output, and Applications",
    "Laplace Transform & Fourier Transform: Comparison and Relationship",
    "Inverse Laplace Transform & Conditions for Existence of Laplace Transform",
    "Properties of Laplace Transform: Linearity, Time Shifting, Frequency Shifting, Time Reversal Etc.",
    "Proof of Properties of Laplace Transform: Linearity, Time & Frequency Shifting, Time Reversal Etc.",
    "ROC in Laplace Transform Explained: Basics, Properties, and Stability",
    "1. ROC & Laplace Transform Solved Examples: Step by Step Solutions",
    "2. ROC & Laplace Transform Solved Examples: Step by Step Solutions",
    "Unilateral Laplace Transform Explained: Basics and Solved Examples",
    "Laplace Transform of Standard Signals",
    "1. Laplace Transform Solved Examples: Step by Step Solutions",
    "2. Laplace Transform Solved Examples: Step by Step Solutions",
    "Impulse Response Solved Examples: Step by Step Solutions",
    "3. Laplace Transform Solved Examples: Step by Step Solutions",
    "Initial and Final Value Theorem: Basics, Conditions, and Solved Examples",
    "Initial and Final Value Theorem Solved Examples: Rules, Procedure, and Step by Step Solutions",
    "4. Laplace Transform Solved Examples: Step by Step Solutions",
    "5. Laplace Transform Solved Examples: Step by Step Solutions",
    "Introduction to Z Transform: Basics, Properties, Relation with DTFT, Inverse ZT & Applications",
    "Z Transform of Finite Discrete Sequence Solved Examples",
    "Inverse Z Transform Solved Examples: Step by Step Solutions",
    "1. Z Transform of Standard Signals Solved Examples",
    "2. Z Transform of Standard Signals Solved Examples",
    "Z Transform of Standard Signals Explained: Impulse, Step, Exponential, Sine and Cosine Functions",
    "Initial and Final Value Theorem in Z Transform: Basics and Solved Examples",
    "Properties of Z Transform Explained: Basics, Proof and Solved Examples",
    "ROC of Z Transform Explained: Basics, Case Studies, Solved Examples, and Stability Identification",
    "ROC and Z Transform Solved Examples: Step by Step Solutions",
    "Causality and Stability from ROC & Z Transform: Basics and Solved Examples",
    "Long Division Method for Inverse Z Transform: Basics and Solved Examples",
    "Direct Method or Partial Fraction Method for Inverse Z Transform Solved Examples",
    "Residue Method for Inverse Z Transform Solved Examples",
    "ROC and Z Transform Solved Examples: Step by Step Solutions",
    "Properties of Z Transform Solved Examples: Step by Step Solutions",
    "Convolution Property of Z Transform Solved Example",
    "Transfer Function & Impulse Response by Z Transform Solved Examples",
    "Comparison of Fourier Series & Fourier Transform",
    "Fourier Series Coefficient Derivation",
    "Types of Fourier Series: Exponential, Trigonometric, and Polar Fourier Series",
    "Properties of Fourier Series Explained: Linearity, Time & Frequency Shifting, Scaling, Symmetry Etc.",
    "Relation between Trigonometric & Exponential Fourier Series Coefficients",
    "Fourier Series Coefficients Solved Examples",
    "Fourier Series Coefficients from Symmetry: Basics and Solved Examples",
    "Fourier Series Solved Examples: Step by Step Solutions",
    "DC Component of Fourier Series Solved Examples: Step by Step Solutions",
    "Fundamental Component & Harmonics of Fourier Series Solved Examples: Step by Step Solutions",
    "1. Trigonometric Fourier Series Solved Examples: Step by Step Solutions",
    "2. Trigonometric Fourier Series Solved Examples: Step by Step Solutions",
    "1. Exponential Fourier Series Solved Example: Step by Step Solutions",
    "2. Exponential Fourier Series Solved Example: Step by Step Solutions",
    "Introduction to Fourier Transform: Basics, Conditions for Existence, and Applications",
    "Derivation of Inverse Fourier Transform using Fourier Series",
    "Fourier Transform of Rectangular Pulse: Step by Step Solutions",
    "Fourier Transform of Impulse Signal: Step by Step Solutions",
    "Fourier Transform of DC Signal: Step by Step Solutions",
    "Fourier Transform of Cosine Signal: Step by Step Solutions",
    "Fourier Transform of Unit Step Signal: Step by Step Solutions",
    "Fourier Transform of Shifted Unit Step Signal: Step by Step Solutions",
    "Fourier Transform of Two Sided Exponential Signal: Step by Step Solutions",
    "Fourier Transform of Standard Signals",
    "Properties of Fourier Transform",
    "Linearity Property of Fourier Transform: Statement, Proof, and Solved Examples",
    "Time Shifting Property of Fourier Transform: Statement, Proof, and Solved Examples",
    "Frequency Shifting Property of Fourier Transform: Statement, Proof, and Solved Example",
    "Differentiation & Integration Properties of Fourier Transform: Statement, Proof, and Solved Example",
    "Time Scaling Property of Fourier Transform: Statement, Proof, and Solved Examples",
    "Multiplication & Convolution Properties of Fourier Transform Solved Examples",
    "Duality Property of Fourier Transform: Statement and Solved Examples",
    "Inverse Fourier Transform Solved Examples: Step by Step Solutions",
    "Distortion Less Transmission of Signal: Magnitude and Phase Response",
    "Fourier Transform Solved Examples: Step by Step Solutions",
    "Correlation of Signals: Basics, Types, Relation & Comparison with Convolution, Applications etc.",
    "Properties of Correlation of Signals: Cross Correlation and Auto Correlation Properties",
    "Proof of Properties of Correlation of Signals: Step by Step Derivation",
    "Correlation Solved Examples: Step by Step Solution",
    "1. Auto Correlation Solved Example: Step by Step Solution",
    "2. Auto Correlation Solved Example: Step by Step Solution",
    "3. Auto Correlation Solved Example: Step by Step Solution",
    "Correlation Solved Example: Step by Step Solution",
    "Parseval's Theorem for Energy Signals: Energy Spectral Density and Solved Example",
    "Classification of Signals | L 1 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Operations on Continuous Time Signals | L 2 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Operations On Independent Variables | L 3 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Addition of Two Continuous Time Signals | L 4 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Standard Signals: Dirac Delta | L 5 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Standard Signals: Unit Step & Unit Ramp | L 6 | Signal Systems | Sankalp GATE 2022 Batch #Vishalsoni",
    "Synthesis and Analysis of Continuous Time Signals | L 7 | Signal Systems | Sankalp GATE 2022 Batch",
    "Standard Signal: Sinc & Sampling Function | L 8 | Signal Systems | Sankalp GATE 2022 Batch",
    "Standard Signal: Greatest & Least Integer Function | L 9 | Signal Systems | Sankalp GATE 2022 Batch",
    "Discrete Time Signals & Operations | L 10 | Signal Systems | Sankalp GATE 2022 Batch",
    "Standard Signals: Impulse Sequence | L 11 | Signal Systems | Sankalp GATE 2022 Batch",
    "Standard Signals: Step & Ramp Sequences | L 12 | Signal Systems | Sankalp GATE 2022 Batch",
    "Synthesis and Analysis of  Discrete time Signals | L 13 | Signal Systems | Sankalp GATE 2022",
    "Even -Odd -NENO Signals | L 313 | Signal Systems | Sankalp GATE 2022 Batch",
    "Conjugate Symmetric and Conjugate Antisymmetric Signals | L 15 | Signal Systems | Sankalp GATE 2022",
    "Continuous Time Periodic - Non Periodic Signals | L 16 | Signal Systems | Sankalp GATE 2022 Batch",
    "Periodicity of Sinusoids and Complex Exponentials | L 17 | Signal Systems | Sankalp GATE 2022 Batch",
    "Discrete Time Periodic - Non Periodic Signals | L 18 | Signal Systems | Sankalp GATE 2022 Batch",
    "Orthogonal - Non orthogonal Signals | L 19 | Signal Systems | Sankalp GATE 2022 Batch",
    "Continuous Time Energy Signals - 1 | L 20 | Signal Systems | Sankalp GATE 2022 Batch",
    "Continuous Time Energy Signals - 2 | L 21 | Signal Systems | Sankalp GATE 2022 Batch",
    "Continuous Time Energy Signals - 3 | L 22 | Signal Systems | Sankalp GATE 2022 Batch",
    "Discrete Time Energy Signals | L 23 | Signal Systems | Sankalp GATE 2022 Batch",
    "Continuous Time Power Signals | L 24 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Power of Periodic Signals | L 25 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Discrete Time Periodic Signals | L 26 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Bounded and Unbounded Signals | L 27 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Basic Systems | L 28 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "STATIC & DYNAMIC Systems  | L 29 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CAUSAL & NON-CAUSAL SYSTEM I 1  | L30 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CAUSAL & NON-CAUSAL SYSTEM I 2 I | L31 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "LINEAR & NON-LINEAR SYSTEM  1  | 32 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "LINEAR & NON-LINEAR SYSTEM  2 | L33 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "TIME INVARIANT & TIME VARIANT SYSTEM - 1 | L34 | Signal Systems |Sankalp GATE 2022 Batch #VishalSoni",
    "TIME INVARIANT & TIME VARIANT SYSTEM -2  | L35 | Signal Systems |Sankalp GATE 2022 Batch #VishalSoni",
    "STABLE & UNSTABLE SYSTEM| L36 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONTINUOUS TIME LTI SYSTEM | L 37 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of Continuous Time Signals | L 38 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of Continuous Time Signals | L 39 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of Continuous Time Signals -3 L 40 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of Continuous Time Signals | L 41 | Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of DISCRETE Time Signals -1  L 42 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "CONVOLUTION Of DISCRETE Time Signals  2 L 43 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Properties of LTI system I  L 44 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Properties of LTI system 2  L 45 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Properties of LTI system 3 L 46 Signal Systems | Sankalp GATE 2022 Batch #VishalSoni",
    "Properties of LTI system 4 L:47  | Sankalp GATE 2022  #VishalSoni",
    "Complete Set Of Mutually Orthogonal Harmonically Related Sinusoids| Sankalp GATE 2022  #VishalSoni",
    "Trigonometric Fourier Series | L:49 | Sankalp GATE 2022  #VishalSoni",
    "Exponential Fourier Series | L:50 | Sankalp GATE 2022  #VishalSoni",
    "Validity of Trigonometric Fourier Series  | L:51 | Sankalp GATE 2022  #VishalSoni",
    "Properties Of Fourier Series Coefficient - 1  | L:52 | Sankalp GATE 2022  #VishalSoni",
    "Properties Of Fourier Series Coefficient - 2  | L: 53  | Sankalp GATE 2022  #VishalSoni",
    "Properties of Fourier Series Coefficient - 3  | L: 54  | Sankalp GATE 2022  #VishalSoni",
    "Heart of Fourier Series : Symmetry In Periodic Graph - 1| L: 55  | Sankalp GATE 2022  #VishalSoni",
    "Heart of Fourier Series : Symmetry In Periodic Graph - 2| L: 56  | Sankalp GATE 2022  #VishalSoni",
    "Exact Calculation Of Fourier Series Coefficient -1  | L: 57  | Sankalp GATE 2022  #VishalSoni",
    "Exact Calculation Of Fourier Series Coefficient -2  | L: 58  | Sankalp GATE 2022  #VishalSoni",
    "Exact Calculation Of Fourier Series Coefficient -3  | L: 59  | Sankalp GATE 2022  #VishalSoni",
    "PARSEVAL THEOREM for Power Signals | L: 60  | Sankalp GATE 2022  #VishalSoni",
    "Drichlet's Condition and Gibb's Phenomenon  | L: 61  | Sankalp GATE 2022  #VishalSoni",
    "Fourier Transform : Basics & Property | L: 62  | Sankalp GATE 2022  #VishalSoni",
    "Properties of Fourier Transform  | L: 63  | Sankalp GATE 2022  #VishalSoni",
    "Fourier Transform of Absolutely Integrable Signal | L: 64  | Sankalp GATE 2022  #VishalSoni",
    "Fourier Transform of Power Signals | L: 65  | Sankalp GATE 2022  #VishalSoni",
    "Special Properties Of Fourier Transform  | L: 66  | Sankalp GATE 2022  #VishalSoni",
    "Special Properties Of Fourier Transform | L: 67  | Sankalp GATE 2022  #VishalSoni",
    "Eigen Values Eigen Function - 1 | L: 68  | Sankalp GATE 2022  #VishalSoni",
    "Marathon Session on Laplace Transform | Part - 1 | GATE 2022 Exam | Vishal Soni",
    "Laplace Transform | Part - 2 | Marathon Session | GATE 2022 Exam | Vishal Soni",
    "Marathon Session on Laplace Transform | Part - 3 | GATE 2022 Exam | Vishal Soni",
    "Marathon Session on DTFT & DTFS  | Part - 1 | GATE 2022 Exam | Kreateryx | Vishal Soni",
    "Signal & System | L:1 | GATE 2021 | Ummeed Crash Course | Vishal Soni",
    "Continuous Time Fourier Series | L:2 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Continuous Time Fourier Transform  | L:3 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Laplace Transform | L:4 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Z Transform - 1 | L:5 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Z Transform - 2 | L:6 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Sampling | L:7 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Discrete-Time Fourier Transform | L:8 | Signal & System | Ummeed Crash Course | Vishal Soni",
    "Discrete Fourier Transform | L:9 | Signal & System | GATE 2021 Ummeed Crash Course | Vishal Soni",
    "Discrete Time Fourier Series  | L:10 | Signal & System | GATE 2021 Ummeed Crash Course #Ummeed",
    "Signal System Top PYQs | Electrical Engineering |Vishal Soni |GATE 2023 |Kreatryx GATE - EE, ECE, IN",
    "Super 10 Problems on Signals | Lec 1 | GATE 2022 | Vishal Soni",
    "Super 50 Questions on Signal System | GATE/ESE 2021 | Vishal Soni",
    "Basics of Signals & Systems | Part-1 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Basics of Signals & Systems | Part-2 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Basics of Signals & Systems | Part-3 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Basics of Signals & Systems | Part-4 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Basics of Signals & Systems | Part-5 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "LTI Systems | Part-1 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "LTI Systems | Part-2 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "LTI Systems | Part-3 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "LTI Systems | Part-4 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Continuous Time Fourier Series | Part-1 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
    "Continuous Time Fourier Series | Part-2 | GATE ECE PYQs | Rajat Kumar AIR 5 GATE ECE 2023",
  ];

  const videoData = videoIDs.map((id, i) => ({
    id: i + 1,
    title: `SAS Video ${i + 1}`,
    thumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`,
    videoUrl: `https://www.youtube.com/embed/${id}`,
    description: videoDescriptions[i] || "",
  }));

  const [selectedVideo, setSelectedVideo] = useState(null);
  const [selectedSection, setSelectedSection] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const openVideo = (v) => setSelectedVideo(v);
  const closeVideo = () => setSelectedVideo(null);

  const renderSection = (key, title, start, end) => (
    <section id={key} className="mb-12">
      <h2 className="text-2xl font-bold mb-4">{title}</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
        {videoData.slice(start, end).map((video) => (
          <div
            key={video.id}
            onClick={() => openVideo(video)}
            className="bg-gray-800 rounded-lg shadow-lg cursor-pointer transform hover:scale-[1.02] transition duration-300 flex flex-row items-start p-3 sm:flex-col sm:p-4"
          >
            <div className="flex-shrink-0 w-2/5 sm:w-full">
              <img
                src={video.thumbnail}
                alt={video.title}
                className="w-full aspect-video object-cover rounded"
              />
            </div>
            <div className="flex-grow min-w-0 pl-3 sm:pl-0 sm:pt-3">
              <h3 className="text-sm sm:text-base font-semibold mb-1 line-clamp-2">
                {video.title}
              </h3>
              <p className="text-xs sm:text-sm text-gray-400 line-clamp-2">
                {video.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );

  return (
    <div className="flex bg-black text-white w-full min-h-screen">
      {/* SIDEBAR */}
      {sidebarOpen && (
        <aside className="fixed top-0 right-0 h-full w-60 bg-gray-900 border-l border-gray-700 p-4 overflow-y-auto z-40">
          <div className="flex items-center justify-between mb-6">
            <h1 className="text-xl font-bold leading-none">Sections</h1>
            <button
              onClick={() => setSidebarOpen(false)}
              className="text-white text-xl font-bold leading-none hover:text-red-500 transition"
            >
              ✖
            </button>
          </div>
          <nav className="space-y-4">
            {[
              ["Neso", "Neso", 0, 13],
              ["Engineering Funda", "Engineering Funda", 313, 429],
              ["Unacademy", "Unacademy", 429, 511],
              ["GATE PYQ", "GATE PYQ", 511, 530],
            ].map(([key, label]) => (
              <button
                key={key}
                onClick={() => setSelectedSection(key)}
                className={`w-full text-left px-3 py-2 rounded transition-all duration-500 ${
                  selectedSection === key
                    ? "bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text"
                    : "text-white hover:bg-gradient-to-r hover:from-purple-400 hover:via-pink-500 hover:to-red-500 hover:bg-clip-text hover:text-transparent"
                }`}
              >
                {label}
              </button>
            ))}
          </nav>
        </aside>
      )}

      {/* CONTENT */}
      <main className={`flex-1 pt-4 p-4 sm:p-8 ${sidebarOpen ? "pr-64" : ""}`}>
        {/* HEADER WITH INLINE TOGGLE */}
        <div className="flex items-center justify-center mb-6 sm:mb-8 relative">
          <h1 className="text-3xl sm:text-4xl font-bold">
            Signal and Systems - Video Lectures
          </h1>
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="absolute right-0 text-3xl sm:text-4xl text-white hover:text-gray-300 transition"
          >
            {sidebarOpen ? "✖" : "⋮"}
          </button>
        </div>

        {selectedSection === null && renderSection("Neso", "Neso ", 0, 313)}
        {selectedSection === null &&
          renderSection("Engineering Funda", "Engineering Funda ", 313, 429)}
        {selectedSection === null &&
          renderSection("Unacademy", "Unacademy Physics", 429, 511)}
        {selectedSection === null &&
          renderSection("GATE PYQ", "GATE PYQ", 511, 530)}

        {selectedSection === "Neso" && renderSection("Neso", "Neso ", 0, 13)}
        {selectedSection === "Engineering Funda" &&
          renderSection("Engineering Funda", "Engineering Funda ", 313, 429)}
        {selectedSection === "Unacademy" &&
          renderSection("Unacademy", "Unacademy Physics", 429, 511)}
        {selectedSection === "GATE PYQ" &&
          renderSection("GATE PYQ", "GATE PYQ", 511, 530)}
      </main>

      {/* VIDEO MODAL */}
      {selectedVideo && (
        <div className="fixed inset-0 bg-black bg-opacity-90 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-900 p-4 sm:p-6 rounded-lg w-full max-w-3xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4 gap-2">
              <h2 className="text-xl sm:text-2xl font-semibold truncate">
                {selectedVideo.title}
              </h2>
              <button
                onClick={closeVideo}
                className="text-white text-lg hover:text-red-500 transition flex-shrink-0"
              >
                ✖
              </button>
            </div>
            <div className="w-full aspect-video mb-4">
              <iframe
                className="w-full h-full rounded"
                src={selectedVideo.videoUrl}
                title={selectedVideo.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>
            <p className="text-gray-300 text-sm sm:text-base">
              {selectedVideo.description}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default SAS;
