import React, { useState } from "react";

const PSP = () => {
 const videoIDs = [
    "jlHkDBEumP0",
"SGDS6NFN-_U",
"PazddUYtz_o",
"Nw9AQoSqCr8",
"K3eo6HtiutM",
"EBV7qaPwgUU",
"V_T5NuccwRA",
"dsCB09XhY1k",
"Sx1Hjr67xO0",
"vUDMJL2wRgs",
"rRdN8zs_q78",
"vUDMJL2wRgs",
"PazddUYtz_o",
"ohrioyQWMhk",
"HOpVbeYMZ6o&t=6s",
"dsCB09XhY1k&pp=0gcJCckJAYcqIYzv",
"AT14lCXuMKI",
"EjavYOFoJJ0",
"xS9EiDkrn1A",
"QN9hnmAgmOc",
"T7AxM7Vqvaw&t=2s",
"vf-cxgUXcMk",
"EjavYOFoJJ0",
"E6jtj-7xJoA",
"qcEBXrqFLe8",
"i3SWaOhjPCY",
"HucJhUkDJuk",
"_FOkG5D4NBo",
"6gVT64lk764",
"dhh5lrXXXYw",
"Ywnv78X7TAg",
"NyT9vvSBoeo",
"tUijuz8aEJA",
"vUsiWt7PHdQ",
"E1_Gg6dURwk",
"lMv8vIqpUsY",
"Z3WjR_KEVjk",
"wgJ1OrvOWGs",
"8XWiUEvp0Mk",
"egUyaWtsQc0",
"LP0acaj3ZLE",
"Gmc5dsIrNUA",
"hOLAoo2p7gM",
"j_3GDNwogRQ",
"eoZp-5lQyqY",
"JYvCVpxGB9w",
"BeVQ8YmgBRQ",
"H5YZKl-XzHY",
"oYuRtXcwXqw",
"oWTnLzWkF5w",
"ySIWMLJI7HI",
"sRCtrviXnLs",
"BHS4iA7bsDk",
"1567inlTJKc",
"BpeIfof3VBk",
"agl3vjzbG2o",
"EqQ6ZZ1V8Rw",
"AauQihC817o",
"IGuoF98qEG0",
"ocX2FN1nguA",
"nohmBtIby_k",
"Z3zUwN98uRQ",
"PLgJsMPSPKec",
"6mTxoCb1m94",
"5v1w0V4GPrE",
"3cSRV_1bzUE",
"LSeyx5qkveU",
"08LWytp6PNI",
"kMwYD03kVk0",
"c3KCnqciBZE",
"ZxqOvg05O6w",
"Q8XOkEqXYks",
"riR0PTY49MA",
"Ev4w7CDNuWE",
"HMBYWhpP8i4",
"FMjWTzPSZKA",
"_iZ3c7V-thw",
"ga_SvTsLzuk",
"EmqelMa54Y4",
"veODe7OvKIA",
"r9X_zqhblsw",
"rzNF4f707Jc",
"1TrgKl8DRk8",
"x_3FKTDkGT8",
"PR6D3sRM4oA",
"HIDHDpI8dps",
"E00P5cZfnFQ",
"LgDABwcKrTw",
"LFPoPHBiWCE",
"la1jAMx_Lzc",
"530jWnBMD2M",
"CFhYszg2y-8",
"IuDJeGqEZ3A",
"qqRUp28pPFk",
"MdSj5aVEZm0",
"TPNYntM-5o4",
"Ayo5St0tMhw",
"i3E5PcyellU",
"EQycVyNOTL8",
"d7r4LKN28iA",
"eR1QpyQabEc",
"Sq0xsFBJ_nM",
"KBzQU2p0dhY",
"6izXC4lg2WU",
"Lh_dUg74R74",
"f--fD8Y0RnA",
"-NbLKVOK0JQ",
"L7KwSw3VRnA",
"xx_IPRSWtGE",
"y4a60WVYBYU",
"dCP5bn2Kee8",
"Me0a2wKD6og",
"szu6LgTP8jU",
"x_G-3x1x9JI",
"l0qlS5C08L0",
"wNiF3uwQNkA",
"yr2bPcDaxVg",
"2aScqfAI3oc",
"gW2xHKk1cBA",
"JNdbsF-78uk",
"RrqH9NFyprw",
"j3Gb19nSWnU",
"qaszuaFXRTA",
"wMI2k951nqs",
"ccoKzyaO0jI",
"KQZIBckWK-s",
"y9fkXBNhPh4",
"fNl1McayZyY",
"8xJdlvAimOs",
"Qwqae2m2vgU",
"LpHnHRI6gLc",
"6Z-silgul48",
"OxkTCgGIWxk",
"azgYvTZD3eo",
"f0Uw1x8albM",
"7lsqAXmBTGE",
"ojhbmh5SJsw",
"LZYgXaMeor0",
"5nmGmYsOzgY",
"4evAXXnHrOw",
"ZIe_j8xAkU4",
"UmeGlPw8cxI",
"HHJpXRyNh-k",
"YYLpsfe9LQ4",
"IriDVVG-Az4",
"l_PqljNFBw8",
"LIbENy2Bo8Y",
"T-UKH3gMSz0",
"5I6MZROOJXw",
"DHy59_kI0CI",
"X49hHg96tkg",
"rp-nVdC6uEg",
"WjUPmLZSsO0",
"LQXueqsbxRU",
"y4EzSnHJj-Q",
"U2MqRhKzOgg",
"ZThwHgNTHUs",
"zHHhcdRzLcc",
"Ar8vS_QpiMw",
"nSg4_IUmt-k",
"L1yWxYGWodw",
"-cycQu5Pz7o",
"T7LRfn0YI8Y",
"b1z3FJ6VJew",
"sqn9jt-emN4",
"wDmUBokWGgA",
"Gd9GBBiX_98",
"pw0uGPmGNl8",
"sF9Fb7Bi0MY",
"InxAy7eI_OE",
"ReBv6sBk8cI",
"6lh7jtb5wgA",

"irqbmMNs2Bo",

"9-GSIN8s5Eo",
"DH9XSZFhCSE",
"QYTESxvQZ-k",
"8zILkPnpD6E",
"EQeq0FUOMWw",
"xABhuUhv0wQ",
"hgkEOPBIYJE",
"xA4go-Pawkk",
"MmThe9aSJbA",
"vEzP8t4nXA4",
"SHkMR09y9v0",
"3S-bJTlisB0",
"FKXrM0Od0Ow",
"xyErAN8kbsY",
"I8wCP1V6Dfc",
"cMHnX_jmf1w",
"LnTBOXvP9vM",

"sPSPK5w4UPSP0",
"VnsmgHEZiLA",
"Im1xqbJmZD8",
"7EfA0cwZGC0",
"XMMmvv4wZtQ",
"AhAz6cOl_DA",
"gCv170-cN_s",
"LM18CB0xEIc",
"07rT0g_N5eY",
"heJ56FVFrZ4",
"_7GPPMQvO84",
"4FCxXG44SFM",
"rso22UR1b2I",
"aCR3SlfZTwg",
"gAC1FGQitdo",
"WXY-r9s0_Rg",
"Q075ZhB_8Eo",
"cJybIb_JvuY",
"Zydf9p1VOGU",
"OAMPGC032AQ",
"jEgiZQLNfiE",
"0OjJc-Qyd4E",
"qwM_c3gF2lw",
"L5en1y4BBQg",
"Pe8LRt5bcaI",
"YxDD_ImhELk",
"LkmH8etAVWA",
"40XRhfcUtaU",
"zaYk09uW-tg",
"2Rsd5mphXnY",
"3_CFbQOSIBI",
"n1jgmsbCA6s",
"pX3H_0oHQvA",
"0EOKOlV8Dbg",
"m8uQ0cJKDM0",
"YqzNgaFQEh8",
"6wucO5fbiQo",
"f0BqwfVACKY",
"3ME0l0trRsE",
"Jy5QILbHKVA",
"JpquiHExpfI",
"6o8aZzU7TGs",
"AQ_rsjONc7o",
"Tz7vBodZqo8",
"RHmURwB-z1I",
"B-xEyhbz0-U",
"7SRd_gZDqCE",
"39iOnAzIzfQ",
"iWQ5rGWmkXw",
"FanAYSSHABU",
"vSIVnsYQrz0",
"PdiLIj943NY",
"nixt_K8kgos",
"euzKnNGLs8U",
"KFl8iyx66fI",
"jBx_COn2ptE",
"41NmcgA1HF0",
"eStBZCSL-gQ",
"1hUF8IAP-P8",
"6nUr72r9sDI",
"_8iq-iTh-Ns",
"Uuyv88Tn9iU",
"qeAwnZ5xQAU",
"k__ZO0e1OHQ",
"Fczwe3h8oJM",
"JXL8NYoVv6U",
"PSPqWMKa--xk",
"fLPqn026DaE",
"HEEzZ7fA9Oo",
"FkbpSvdE6Z8",
"e6MxeC7htSE",
"iIqjvB22APU",
"YPSPJ7fDmyjI",
"ABYpwVjuDN0",
"rHoOWG6Ihs4",
"ceODxfZWZIo",
"NRA46yNC_P0",
"SJ7oEgpTdDE",
"ZVxTouF8WTU",
"e8NZrbhKXDs",
"_rr2AgzB8RI",
"R8IogBSLXV0",
"loa5eBDONHw",
"2aJzGL_cKzY",
"_fHTUj6BzY0",
"LZNxRSoEG2M",
"jNom4U0B3Y0",
"kMAg6diYCI0",
"lEvpLI50MSU",
"N71-P0i4qPY",
"vWuxWxGVMC8",
"6Zd69FQpc3A",
"PtSHcou0WIs",
"qhJLVxXMBE8",
"CK7Xue5Y9Kw",
"9r3WX0mDG4o",
"UL12Lumo1AM",
"vnGgSU28hU8",
"Zn_YyKpE2AE",
"5nyMb7hJ7Xs",
"tx37dJZTfMM",
"5OFLit1Zf-Q",
"3jnrbtoWgDo",
"kQuHxfPS9xE",
"DJq9SjMGSys",
"lupu1oeS7JE",
"lXr6KKha-ig",
"i0pOPx5Xltw",
"p8-DGGL1Rk0",
"c8-Bl50vjHk",
"Jtn_NXLvbAQ",
"rPxe7t3fmeo",
"Hb0sQVEnxCg",
"5OpitQe0o5k",
"6xRSNSja1mE",
"_2MAktbQO5o",
"G_WjTIBTMhY",
"WK2VR6Br2AU",
"-8esr14bCCI",
"5mIvuE4ugOg",
"0jDiBM68NGU",
"0niA5Wzhwpg",
"7OIZ_W75lAM",
"w0mgn6OLKUs",
"AAF207cxbXk",
"LeWuki7AQLo",
"RVqdK6WAjUI",
"9A5YDGSQy9o",
"5a4jsVMfjlg",
"1uf75EJsveU",
"cDxIGjnKsS8",
"tGgl6EMZxLU",
"p6uqGop26es",
"DExMskdAPO4",
"JKR0S84xLJ4",
"vpdraEnrFnU",
"Wqm1tSzmqkY",
"CskiW4kd6Kk",
"4_2BEgOFd0E",
"zuKqVTbIXOI",
"DSZ4pNCoYZY",
"Vp6OELK4gmo",
"4-KDj-vVk2E",
"zHZx9ByTo2s",
"lAqH2dt7g5I",
"W3dtyZr8rcY",
"N5D5tGTURpk",
"skqCnhhA0ZY",
"q6e6H2Ogsh0",
"Flk5yrlx5Qo",
"viREXI8tvNc",
"0SkdAoVzWpk",
"ct5J8pm_33g",
"PThPm24wGEo",
"Zd5OThnCZ7w",
"5k3t4uaDU30",
"Lie-jO2cpSY",
"CzAgM5bez-g",
"fzW-qP4JdVI",
"g_gganqwPSPw",
"tDAxTQFZB28",
"0dXJKOeqGGA",
"0pjtn6HGPVI",
"rbVt5v8NNe8",
"0UJX96_ZpVE",
"7ZFgphYJvUA",
"X-1qodkHCHo",
"fsoohJiC4r4",
"oMXhxPSPznoc",
"7g_w-cxgZB4",
"vJLt_VG8bqA",
"wZ0BxDNQTCw",
"1F8F4Ma1btM",
"H-dehw4nLVM",
"0HDvRIUodcg",
"lxAReU_RKSo",
"laIQbFLznRo",
"MbDwut1b1hE",
"wnjYD_euSJQ",
"1OZMcC0euic",
"Oa_ji3dDFew",
"27KzMEnwsEM",
"ByLrbQibG9g",
"Oq2IYFiq-AM",
"nxCnKVMGAFs",
"6FaWbQAwpDY",
"0JMObBs9xWQ",
"CoecB74aSV0",
"x0s2k06uYTg",
"2zH5TDg3LUo",
"MiqLsSFrQP0",
"4iaYlp-axac",
"LQytHnI8z7o",
"50qJ3bNm_S0",
"nrvLkjfsJx4",
"YKoM4udWNKM",
"IV2kIss1DIk",
"rzWq24bYuvo",
"3YFMiDk3TvE",
"0CyNbF_pcrY",
"x2-QWbhUV7A",
"25BeWHutGs0",
"OH2s5jBQXvM",
"Gaq10GBlRJA",
"oxOsk4kM9EI",
"6A8cM947CEg",
"4sIdcbHbIbQ",
"EMTrjulX2dU",
"6-XfbfZmOqc",
"89aAkG68yoM",
"vQno9S3yF80",
"xef-jecZPPw",
"vPwvqbSU13A",
"BrO7hfdC8So",
"rMOF82jCq4o",
"yMOtjV1NuGw",
"OcjBc_1e3M8",
"lm0ZSSYP0hg",
"cUky0mPMwBw",
"nIJvKd5I1cY",
"x7NJoUlyXEs",
"kU-_WPIA3ys",
"aF9WrmuRrKU",
"zQbX6r8MagM",
"iXMQs1HBQi8",
"YjxKYxpf51E",
"y3rnTVwWmBY",
"liwJ3Gr-6z0",
"tG--A0ZMLnA",
"rHdBxp4oseA",
"mJVchgjkgL8",
"KSc4zf5t6I4",
"mIIvVze8xWc",
"pQOJT4C6ypk",
"fQI9phlnVb8",
"iZLtYIbRRuE",
"4E0IVfYJZcQ",
"lSiA2S0WjCA",
"BUNzco2GkBA",
"7PkOSbm5XnQ",
"dG1HBSArgjM",
"8-NGTIExdKQ",
"mCfACbalIvc",
"wENmybEjyjo",
"plcWVEzH5PI",
"HZc57hqkmjU",
"ZO8SdOyhDJs",
"jT-fh-fvJDo",
"4xlJ7eWL-ok",
"nRmEWUQ2nQ8",
"VT5jaa_-oMQ",
"0xk-Xbiv5oE",
"LML3kmD1CtI",
"29U5PZfniYs",
"2tgDzFSip00",
"IesFHiWbs7M",
"1W0hs55TLnQ",
"dxrKTGGsGqI",
"dad8Tnm1xYs",
"RaHlFhPymQE",
"f9_RYPjvhr0",
"MjDAQ_yeNmk",
"0H9kxHXZrgs",
"qkvtPbM3A1o",
"WcagDRFHeMo",
"80AuxBTYSeA",
"_3-R2l0mh7w",
"LaVEDKSTYQs",
"bQgRTianPRI",
"OLEJy2gmvug",
"pMEWGLlairs",
"vPpmd0i7SD0",
"cAVpNjpOiZU",
"Ev7ZkWCHHoU",
"jEYDa-zeg64",
"wFerwn5RiWE",
"hZeNI901HwA",
"cDvA89WpgMw",
"8ztkE0YxWes",
"c7ng6QEvmxk",
"XidlkXpowb0",
"eb5w_E1LhcM",
"bpP6MRDXRSs",
"PVaIb2Y-Avw",


  ];

  const videoDescriptions = [
    "7.7 Merge Sort in Data Structure | Sorting Algorithms| DSA Full Course",
"Introduction to Data Structure and Algorithm | DSA Placement Course",
"LeetCode Questions on Arrays| Must-Solve Questions for Placements & Interviews | With JAVA Code",
"How to Search & Apply for Jobs & Internships in 2025 | StPSP by StPSP Guide for Students",
"Roadmap to Crack Service-Based Companies in 2025 | TCS, Wipro, Infosys PrPSParation Guide",
"Internship in Japan for Indian Students | No Japanese Required | Fully Funded | Apply Now",
"7.2 What is Binary Search | Binary Search Algorithm with example | Data Structures Tutorials",
"Software Developer Internship | ₹15000/Month Stipend | Closing Soon",
"File Handling in Python | Python Tutorials for Beginners #lec95",
"AMD India is Hiring Interns | June 2025 | Work on CPUs, GPUs & AI Projects",
"Binary Search Algorithm | Theory + Code | DSA Placement Series",
"AMD India is Hiring Interns | June 2025 | Work on CPUs, GPUs & AI Projects",
"LeetCode Questions on Arrays| Must-Solve Questions for Placements & Interviews | With JAVA Code",
"Multi Dimensional Arrays in JAVA|  DSA with JAVA Course",
"Infosys Springboard Internship 2025 | Free Online Internships for College Students | June Batch",
"Software Developer Internship | ₹15000/Month Stipend | Closing Soon",
"1.1 Arrays in Data Structure | Declaration, Initialization, Memory rPSPresentation",
"C_01 Introduction to C Language | C Programming Tutorials",
"Comment Box 3 | Ma'am Are You Married ?",
"7.6 Quick Sort in Data Structure | Sorting Algorithm | DSA Full Course",
"Lec 1:  Introduction to DBMS | Database Management System",
"6.2 BFS and DFS Graph Traversals| Breadth First Search and DPSPth First Search | Data structures",
"C_01 Introduction to C Language | C Programming Tutorials",
"C_02 Low level vs High level Languages | Machine and Assembly Language | Programming in C",
"C_03 Language Translators | Compiler | Interpreter | Assembler | C Programming Tutorials",
"C_04 Features of C Language | Use of C Language | C Programming Tutorials",
"C_05 Structure of a C Program | Programming in C",
"C_06 Execution Process of a C Program | C Programming Tutorials",
"C_07 Constants in C | Types of Constants | Programming in C",
"C_08 Variables in C Programming | C Programming Tutorials",
"C_09 Keywords and Identifiers | Programming in C",
"C_10 Data Types in C - Part 1 | C Programming Tutorials for Beginners",
"C_11 Data Types in C - Part 2 | Programming in C",
"C_12 Data Types in C - Part 3 | C Programming Tutorials",
"C_13 Operators in C - Part 1 | Unary , Binary and Ternary Operators in C | C programming Tutorials",
"C_14 Operators in C - Part 2 | Arithmetic & Assignment Operators | C Programming Tutorials",
"C_15 Operators in C - Part 3  |  C Programming Tutorials",
"C_16 Operators in C - Part 4  |  C Programming Tutorials",
"C_17 Operators in C - Part 5 (Logical Operators) |  C Programming Tutorials",
"C_18 Operators in C - Part 6 | Bitwise Operators |  C Programming Tutorials",
"C_19 Operators in C - Part 7 (Bitwise Operators-II) |  C Programming Tutorials",
"C_20 Operators in C - Part 8 | Comma Operator |  C Programming Tutorials",
"C_21 Operators Precedence and Associativity in C | C programming Tutorials",
"C_22 Common Errors done by Beginners while writing Programs | C programming tutorials",
"C_23 Formatted Input Functions in C Language || C Programming",
"C_24 Formatted Output Functions in C Language | printf() function in C | C Programming Tutorials",
"C_25 Unformatted Input Functions in C | C Programming Tutorials",
"C_26 Unformatted Output Functions in C | C Programming Tutorials",
"C_27 If Statement in C | C Programming Tutorials",
"C_28 If-Else Statement in C | C Programming Tutorials",
"C_29 Nested If in C | C Programming Tutorials",
"C_30 else if ladder in C | C Programming Tutorials",
"C_31 Switch Statement In C | C Programming Tutorials",
"C_32 C Program to make simple calculator using Switch Case | C Language Tutorials",
"C_33 Introduction to Loop in C Language | Need of loops| C Language Tutorials",
"C_34 For loop in C  | C Programming Tutorials",
"C_35 Properties of For loop in C | C Programming Tutorials",
"C_36 C Program to Print Table of a Number | C Language Tutorials",
"C_37 While Loop in C (part-1) | C Language Tutorials",
"C_38 While Loop in C (part-2) | C Language Tutorials",
"C_39 Do while loop in C with program | C Programming Tutorials",
"C_40 Difference between for, while and do while loop in C | C Programming Tutorials",
"C_41 Break statement in C | C Language Tutorials",
"C_42 Continue Statement in C | C Programming Tutorials",
"C_43 Need of Nested Loops in C | Nested For loop in C",
"C_44 Nested while loop in C | C Programming Tutorials",
"C_45 Nested do while loop in C | C Programming Tutorials",
"C_46 Arrays in C - part 1 | Introduction to Arrays",
"C_47 Arrays in C - Part 2 | Initialization of arrays in C programming",
"C_48 Arrays in C- part 3 | Memory RPSPresentation and Accessing of Array elements",
"C-49 Arrays in C - Part 4 | Array Program 1 | C Programming Tutorials",
"C-50 Arrays in C - Part 5 | Array Program 2 | C Programming Tutorials",
"C-51 Arrays in C - Part 6 | Array Program 3 | C Programming Tutorials",
"C_52 Arrays in C - part 7 | Array Program 4 | C Programming",
"C_53 Introduction to Two Dimensional (2D) Arrays in C",
"C_54 Two Dimensional(2D) Arrays in C | Initialization of 2D Arrays",
"C_55 Access Array Elements |Memory RPSPresentation of 2D Arrays | C Programming Tutorials",
"C_56 2D Arrays Program 1| Program to print Matrix and calculate Sum | C Programming",
"C_57 Two Dimensional Array program 2 | Program to print Transpose of Matrix",
"C_58 Program to print Sum of individual Rows and Columns of a Matrix | C Programming",
"C_59 Program to add Two Matrix in C | C language tutorials",
"C_60 C program for Matrix Multiplication part 1 | C Language Tutorials",
"C_61 C program for Matrix Multiplication part2 | C Language Tutorials",
"C_62 Strings in C - part 1 | C programming tutorials",
"C_63 Strings in C-part 2 | Read a String using scanf and gets function",
"C_64 Strings in C- part 3 | printf and puts function in C",
"C_65 C Program to Read and Print a String | C Programming Tutorials",
"C_66 Program to Find Length of a String | C Programming Language",
"C_67 C Program to concatenate two strings | with strcat() and without strcat()",
"C_68 C program to Compare two Strings | with strcmp() and without strcmp() function",
"C_69 C Program to Reverse a String | with strrev() and without strrev() function",
"C_70 C Program to convert a String from Upper Case to Lower Case |with strlwr() and without strlwr()",
"C_71 Pointers in C - part 1| Introduction to pointers in C | C Programming Tutorials",
"C_72 Pointers in C- part 2 |Address of(&) and Indirection (*) operator in Pointers I C Programming",
"C_73 Pointers in C- part 3 | Pointer Assignment",
"C_74 Pointers in C- part 4 | Pointer to Pointer (Double Pointer)",
"C_75 Pointers in C-part 5 | Pointer Arithmetic (Addition) with program",
"C_76 Pointers in C- part 6 | Pointer Arithmetic (Subtraction) with program",
"C_77 Pointers in C- part 7 | Pointer Arithmetic (Increment/Decrement) program",
"C_78 Problems on Pointers | Important question with answer",
"C_79 Coding Problems on Pointers | Important Question with Answer",
"C_80 Void Pointer in C | Detailed explanation with program",
"C_81 Null Pointer in C | C Programming Tutorials",
"C_82 What is Dangling pointer in C | C Language Tutorials",
"C_83 What is Wild Pointer in C | C Language Tutorials",
"C_84 Introduction to Functions - part 1 | C Language Tutorials",
"C_85 Function in C - part 2 | Function Declaration with program",
"C_86 Functions in C-part 3 |Function Definition in C",
"C_87 Functions in C- part 4 |Call by Value & Call by Reference in C",
"C_88 Functions in C -part 5 | Function with No Argument No Return Type",
"C_89 Functions in C - part 6 | Function Without Argument With Return Type",
"C_90 Functions in C-part 7 | Function With Argument Without Return Type",
"C_91 Functions in C- part 8 | Function With Argument and Return Type",
"C_92 Solved Problem on Functions in C | GATE Question with Answer",
"C_93 Solved problem on Functions in C GATE Question with Answer",
"C_94 Solved Problem on Functions in C |Gate Question with Answer",
"C_95 Solved Problem on Functions in C | GATE question with answer",
"C_96 Passing Array as an Argument to a Function in C | C Language Tutorials",
"C_97 Passing String as an Argument to a Function | C Language Tutorials",
"C_98 Return a String from a Function in C | C Language Tutorials",
"C_99 Returning Pointer from Function in C | C Language Tutorials",
"C_100 Solved Problem on Functions in C | GATE Question with Answer",
"C_101 Function Pointers in C | Pointer to Function | C Programming Tutorials",
"C_102 Callback Function using Function Pointer in C | C Language Tutorials",
"C_103 Application of Function Pointer in C | Array of Function Pointer",
"C_104 Recursion in C | Introduction to Recursion",
"C_105 Recursion in C - part 2 | Problem on Recursion",
"C-106 Types of Recursion-part 1 | Direct and Indirect Recursion",
"C_107 Types of Recursion-part 2 | Tail and Non-Tail Recursion",
"C_108 Recursion Solved Problem (GATE 2016 Question) | C Programming Tutorials",
"C_109 Structures in C - part 1| Introduction to Structures",
"C_110 Structures in C-part 2 | Declaring Structure Variables/Objects",
"C_111 Structures in C-part 3 | Initializing & Accessing of Structure Members",
"C_112 Array of Structures in C | C Language Tutorials",
"C_113 Pointer to Structure in C | Structure Pointer | C Language Tutorials",
"C_114 Unions in C | C Language Tutorials",
"C_115 Structures in C using typedef | C Language Tutorials",
"C_116 Structure Padding in C | C Language Tutorials",
"C_117 Structure Packing in C | C Language Tutorials",
"C_118 Problems on Structures in C | Designated Initialization in Structures",
"C_119 File Handling in C - part 1 | Introduction to Files",
"C_120 File Handling in C - part 2 | File Pointer and fopen() function",
"C_121 File Handling in C - part 3 | Writing in a File in C Language",
"C_122 File Handling in C - part 4 | Read From File in C | C Programming Language",
"C_123 Append Mode in File Handling | C Programming Language",
"C_124 r+ Mode in File Handling | C Programming Language",
"C_125 w+ mode in File handling | C programming Tutorials",
"C_126 a+ mode in File Handling | C Programming Tutorials",
"C_127 fseek() function in File Handling | C Language tutorials",
"C_128 ftell () function in File Handling | C Programming Language",
"C_129 rewind() function in File Handling| C Programming Tutorials",
"C_130 C Program to Count no of Lines in a Text File | File Handling in C",
"C_131 C program to copy content of one file into another file | File Handling in C",
"C_132 Introduction to Dynamic Memory Allocation in C  | SMA vs DMA",
"C_133 Dynamic Memory Allocation using malloc() | C Language Tutorials",
"C_134 Dynamic Memory Allocation using calloc() | C Language Tutorials",
"C_135 Dynamic Memory Allocation using realloc() | C Language Tutorials",
"C_136 Deallocating the Dynamically Allocated Memory using free() | C Programming Tutorials",
"C_137 Memory Leak in C | C Programming Language",
"C_138 Enumeration in C | enum data type in C Language",
"C_139 Enum in C | Technical Interview Questions and Answers",
"C_140 Storage Classes in C | C Language tutorials",
"C_141 Types of Storage Classes in C - part 1 | auto storage class",
"C_142 Types of Storage Classes in C - part 2 | register storage class",
"C_143 Types of Storage Classes in C - part3 | Static Storage Class",
"Types of Storage Classes in C - part 4 | extern storage class | Lecture 144 | C Programming Course",
"C_145 Solved Problems on Storage Classes in C | Technical Interview Question",
"C_146 Introduction to Pre-processor in C| PrPSProcessor Directive  #include | C Programming Tutorials",
"C_147 Storage Classes | Gate Question on Storage Classes in C",
"C_148 Macro in C | PrPSProcessor command #define and #undef  in C | C Programming Tutorials",
"C_149 Predefined Macros in C | Conditional Pre-processor Commands | C Programming Tutorials",
"Good News 🙈😃 | Completed C Programming Course",

"C Language Tutorial for Beginners (with Notes & Practice Questions)",

"C Program to Generate Multiplication Table of a Given Number",
"C Program to Find Sum Of First n Natural Numbers in O(1)",
"C Program to Find Largest Element in an Array",
"C Program to Find Prime Number",
"C Program to Convert Decimal Number to Binary Number",
"C Program to Reverse a Number",
"C Program to Calculate Factorial of a Number",
"C Program to Print Star Pattern - 1",
"C Program to Reverse a String",
"C Program To Print Prime Numbers In A Given Range",
"C Program To Print Star Pattern - 2",
"C Program To Print Star Pattern - 3",
"C Program To Print Star Pattern - 4",
"C Program To Print Number Pattern - 1",
"C Program To Print Star Pattern - 5",
"C Program to Count Number of Digits in an Integer",
"C Program to Calculate Power of a Number",

"Find the Minimum Number in an Array | C Programming Example",
"Find the Maximum Number in an Array | C Programming Example",
"Count the Occurrences of a Value in an Array | C Programming Example",
"Reverse An Array | C Programming Example",
"Check If A String Is A Palindrome | C Programming Example",
"Sum the Values in an Array | C Programming Example",
"Compute the Average of an Array | C Programming Example",
"Convert Celsius to Fahrenheit | C Programming Example",
"Computing the Fibonacci Sequence | C Programming Example",
"Counting the Vowels in a String | C Programming Example",
"String append (i.e. concatenation) with dynamic memory allocation | C Programming Example",
"Dice roll simulator | C Programming Example",
"Flip a string's lowercase characters to uppercase and vice versa | C Programming Example",
"Create a copy of an array | C Programming Example",
"Determine if a year is a leap year | C Programming Example",
"hello world | C Programming Example",
"Vector Addition | C Programming Example",
"Dot Product | C Programming Example",
"Counting Occurrences Of A Word In A String | C Programming Example",
"Removing all occurrences of a character from a string | C Programming Example",
"Convert binary to decimal | C Programming Example",
"RPSPlace a character in a string with another character | C Programming Example",
"Infinite Input Buffer | C Programming Example",
"Converting Kilometers To Miles | C Programming Example",
"String Format Validation | C Programming Example",
"Area of a Circle | C Programming Example",
"Output a Triangle of Stars | C Programming Example",
"Remove All Vowels From A String | C Programming Example",
"Check If Arrays Are Disjoint | C Programming Example",
"Rotate An Array Left | C Programming Example",
"Rotate An Array Right | C Programming Example",
"Merge Two Sorted Arrays | C Programming Example",
"Count Non-RPSPeating Array Elements | C Programming Example",
"Manually Find The Length Of A String | C Programming Example",
"Program That Prints Its Own Source Code | C Programming Example",
"Bubble Sort | C Programming Example",
"Sum The First N Natural Numbers Using Recursion | C Programming Example",
"Trim Leading Whitespace String Characters | C Programming Example",
"Remove Trailing Whitespace String Characters | C Programming Example",
"Reverse The Words In A String | C Programming Example",
"Count The Words In A String | C Programming Example",
"Find Length Of Longest Word In A String | C Programming Example",
"Find Length Of Smallest Word In A String | C Programming Example",
"Insertion Sort | C Programming Example",
"Print Unique Elements Of An Array | C Programming Example",
"Compute Standard Deviation | C Programming Example",
"Count The Punctuation Marks In A String | C Programming Example",
"Check If Words Are Anagrams | C Programming Example",
"Use Recursion To Print String In Reverse | C Programming Example",
"Print First Unique Character In A String | C Programming Example",
"Print First RPSPeating Character In A String | C Programming Example",
"Count Occurrences Of Each Character In A String | C Programming Example",
"Print A String Until The First Newline Character | C Programming Example",
"Find The Minimum Occurring Character In A String | C Programming Example",
"Find The Maximum Occurring Character In A String | C Programming Example",
"Verify Password Requirements | C Programming Example",
"Number Guessing Game | C Programming Example",
"Create A Menu Using A Switch Statement | C Programming Example",
"Coin Toss Simulator | C Programming Example",
"Remove a character from a string at a specified position | C Programming Example",
"Make All String Letters Lowercase | C Programming Example",
"Binary Search Algorithm | C Programming Example",
"Fizz Buzz Problem | C Programming Example",
"Find The Second Highest Number In An Array | C Programming Example",
"Find The Second Lowest Number In An Array | C Programming Example",
"Count The Letters In A String | C Programming Example",
"Count The Digits In A String | C Programming Example",
"Read A File And Display Its Contents | C Programming Example",
"Write Lines Of User Input To A File | C Programming Example",
"Find The Largest Number In A File | C Programming Example",
"Compute Average Of Numbers In A File | C Programming Example",
"Lottery Number Generator | C Programming Example",
"Selection Sort | C Programming Example",
"Append Text To A File | C Programming Example",
"Using qsort() To Sort An Array | C Programming Example",
"Copy A File | C Programming Example",
"Delete A Specific Line From A File | C Programming Example",
"Merge Contents Of Two Files Into A Third File | C Programming Example",
"Split A String At An Index Into Two Strings | C Programming Example",
"Rock Paper Scissors Game | C Programming Example",
"Coding Trick To Initialize An Array With Include Directive And External File | C Programming Example",
"How To Return More Than One Value From A Function | C Programming Example",
"Word Scramble Game | C Programming Example",
"Magic 8-Ball Game | C Programming Example",
"Sum The Digits Of A Number | C Programming Example",
"Sorting An Array Of Strings | C Programming Example",
"Sort Three Numbers | C Programming Example",
"Find The Average Of Groups Of Numbers In A File | C Programming Example",
"How To Create A Substring Function | C Programming Example",
"Check If A String Ends With Another String | C Programming Example",
"Check If A String Starts With Another String | C Programming Example",
"Check If An Integer Is Even Or Odd | C Programming Example",
"Reverse A String | C Programming Example",
"Return Multiple Dynamically Allocated Arrays From A Function | C Programming Example",
"Move All Zeros In An Array To The End | C Programming Example",
"Split Even And Odd Values Of An Array Into Two Arrays | C Programming Example",
"Compute Volume Of A Sphere | C Programming Example",
"Count The Occurrences Of A Character In A String | C Programming Example",
"Delete All File Lines That Match A String | C Programming Example",
"Initialize An Array With User Input | C Programming Example",
"Check If A String Is A Substring Of Another String | C Programming Example",
"Fill An Array With Random Numbers | C Programming Example",
"How To Generate Random Double Numbers | C Programming Example",
"RPSPlace All Occurrences Of A Value In An Array With Another Value | C Programming Example",
"Savings Calculator With A Yearly Investment Returns Table | C Programming Example",
"Create A Multiplication Table | C Programming Example",
"Reverse An Integer Number | C Programming Example",
"Using Recursion To Compute The Average Of An Array | C Programming Example",
"Initialize A 2D Array With User Input | C Programming Example",
"How To Check For Matrix Equality | C Programming Example",
"Matrix Addition | C Programming Example",
"Matrix Subtraction | C Programming Example",
"Check If A Number Is An Armstrong Number | C Programming Example",
"Find The Transpose Of A Matrix | C Programming Example",
"Fill A 2D Array With Random Values | C Programming Example",
"Print Numbers From 00-99 In A 10x10 Grid | C Programming Example",
"Matrix Multiplication | C Programming Example",
"Swap Two Rows In A 2D Array | C Programming Example",
"Swap Two Columns In A 2D Array | C Programming Example",
"Check If A Value Is In An Array | C Programming Example",
"Quicksort Algorithm Implementation | C Programming Example",
"Print A Christmas Tree | C Programming Example",
"Shuffle An Array | C Programming Example",
"Read A Specific Line From A File | C Programming Example",
"Count The Number Of Lines In A File | C Programming Example",
"Merge Sort | C Programming Example",
"Set Data Structure And Operations | C Programming Example",
"Array Index Coding Trick | C Programming Example",
"Technique To Optionally Activate Debug Output Code | C Programming Example",
"Delete All Array Elements That Match A User Input Value | C Programming Example",
"Find The Minimum Distance Between Two Different Numbers In An Array | C Programming Example",
"RPSPlace All Occurrences Of A Substring In A String With Another Substring | C Programming Example",
"Delete All Occurrences Of A Substring From A String | C Programming Example",
"Swap Two Variables Without A Temporary Variable (XOR Swap Algorithm) | C Programming Example",
"RPSPlace A Specific Line In A File | C Programming Example",
"Find And Print The Longest Word In A String | C Programming Example",
"Share A Global Variable Across Multiple Files By Using extern | C Programming Example",
"Write To A Specific Line Of A File And Shift Down The Remaining Lines | C Programming Example",
"Dynamically Allocate Memory For An Array Of Strings | C Programming Example",
"Join Strings Function | C Programming Example",
"Convert Decimal Number To Binary Number | C Programming Example",
"Split Strings Function | C Programming Example",
"Check If A String Is A Rotation Of Another String | C Programming Example",
"A Better Seed For Random Number Generation Than The Current Time | C Programming Example",
"Check If A Number Is Prime | C Programming Example",
"Advanced Integer Input Validation | C Programming Example",
"Print A Heart | C Programming Example",
"How To Safely Handle realloc() Failure | C Programming Example",
"Reverse A File | C Programming Example",
"Stack Data Structure And Operations | C Programming Example",
"Find And Print The Smallest Word In A String | C Programming Example",
"Read And Write An Array Of Structs To A Binary File | C Programming Example",
"Create Your Own strcpy() String Copy Function | C Programming Example",
"Create Your Own memcpy() Memory Copy Function | C Programming Example",
"Read Char From File Portability Bugs + Fix | C Programming Example",
"Find The Index Of K In A Sorted Array OR Where It Belongs To KPSPSP It Sorted | C Programming Example",
"Remove All Occurrences Of A Char From A File (Without Using A Temp File) | C Programming Example",
"Read All File Contents Into A String | C Programming Example",
"Merge Two Sorted Arrays Using Recursion | C Programming Example",
"Calculate String Length Using Recursion | C Programming Example",
"Delete All Lines From A File That Contain A Char From A Group Of Chars | C Programming Example",
"Count The Vowels In A String Using Recursion | C Programming Example",
"List All Files And Directories In A Directory (POSIX Library) | C Programming Example",
"Read CSV File Data Into An Array Of Structs | C Programming Example",
"Remove Trailing Newline Character From fgets() Input | C Programming Example",
"Write An Array Of Structs To A CSV File | C Programming Example",
"Read And Store Each Line Of A File Into An Array Of Strings | C Programming Example",
"Create Your Own tolower() Function | C Programming Example",
"Create Your Own strspn() Function | C Programming Example",
"Remove A Directory Using _rmdir() On Windows | C Programming Tutorial",
"Remove Duplicate Array Elements | C Programming Example",
"Find The Third Angle Of A Triangle | C Programming Example",
"Add Two Numbers From User Input | C Programming Example",
"Count The Number Of Words And Characters In A File | C Programming Example",
"Compute The Product Of All Array Elements | C Programming Example",
"Calculate The Litres Of Paint Required To Paint A Fence | C Programming Example",
"Random Password Generator | C Programming Example",
"Add Line Numbers To A File | C Programming Example",
"Fill An Array With Unique Random Numbers | C Programming Example",
"Find The Frequency Of Each Letter In A String | C Programming Example",
"Read All File Contents Into A Dynamically Allocated String | C Programming Example",
"Store An Unknown Infinite Amount Of Numbers From User Input Into A Buffer | C Programming Example",
"Shuffle A 2D Array | C Programming Example",
"Round A Double To A Specific Number Of Decimal Places | C Programming Example",
"Create Your Own strchr() Function | C Programming Example",
"Area Of A Rectangle Calculated Using User Input Values | C Programming Example",
"Area Of Triangle Calculated Using User Input Values | C Programming Example",
"Print An Array In Reverse | C Programming Example",
"Truncate A String | C Programming Example",
"Concatenate Two Arrays | C Programming Example",
"Truncate A Dynamically Allocated String | C Programming Example",
"Remove Duplicate Characters From A String | C Programming Example",
"Linear-Time Algorithm To Remove Duplicate Characters From A String | C Programming Example",
"Perimeter Of A Rectangle Calculated Using User Input Values | C Programming Example",
"Split An Array At A Specific Index | C Programming Example",
"Reverse An Array Using Recursion | C Programming Example",
"Convert The Vowels In A String To Uppercase | C Programming Example",
"Insert A Value At Random Indexes In A 2D Array | C Programming Example",
"Find The Two Array Elements Whose Sum Is Closest To Zero | C Programming Example",
"Count The Occurrences Of A Character In A String Using Recursion | C Programming Example",
"Cylinder Volume Calculated Using User Input Values | C Programming Example",
"Remove All The Characters In A String That Occur In Another String | C Programming Example",
"Count The Unique Elements In An Array | C Programming Example",
"Read Numbers In A File Into A 2D Array | C Programming Example",
"Find Sum And Average Of Each Row In 2D Array | C Programming Example",
"Find Sum And Average Of Each Column In A 2D Array | C Programming Example",
"Print An Array | C Programming Example",
"Area Of A Square | C Programming Example",
"Calculate Factorial Using Recursion | C Programming Example",
"Calculate Factorial Using A Loop | C Programming Example",
"Read All File Lines Into A Dynamically Allocated Array Of Strings | C Programming Example",
"Delete An Array Element At A Specific Index | C Programming Example",
"Find The Maximum Number In An Array Using Recursion | C Programming Example",
"Find The Minimum Number In An Array Using Recursion | C Programming Example",
"Create Your Own strcat() Function | C Programming Example",
"Find The First Occurrence Of A Character In A String | C Programming Example",
"strpbrk() Function Implementation | C Programming Example",
"Find The Last Occurrence Of A Character In A String | C Programming Example",
"strncpy() Function Implementation | C Programming Example",
"Insert A Value Into An Array At A Specific Position | C Programming Example",
"Return Early Pattern | C Programming Example",
"Print A 2D Array | C Programming Example",
"Check If An Array Is Sorted | C Programming Example",
"Check If A String Is A Palindrome Using Recursion | C Programming Example",
"Initialize An Array Of Strings With User Input | C Programming Example",
"Queue Data Structure & Operations (Linked List Based) | C Programming Example",
"Remove All Space Characters In A String | C Programming Example",
"Remove Consecutive Spaces In A String | C Programming Example",
"Quiz Game | C Programming Example",
"Calculate Circle Circumference With User Input Radius | C Programming Example",
"Send An HTTP Request | C libcurl Library Introduction",
"Store HTTP Response Into A String | C libcurl Library",
"Find The Most Frequent Value In An Array | C Programming Example",
"Remove Non Alphabet Characters A From String | C Programming Example",
"Print A Specific Row In A 2D Array | C Programming Example",
"Print A Specific Column In A 2D Array | C Programming Example",
"Check If All String Characters Are Unique | C Programming Example",
"Iterate Through A String Using A Pointer | C Programming Example",
"Check If A Number Is Prime Using Recursion | C Programming Example",
"Check If A Number Is Positive, Negative Or Zero | C Programming Example",
"Countdown Timer | C Programming Example",
"Simple Calculator | C Programming Example",
"Find Factors Of A Number | C Programming Example",
"Measure The Execution Time Of A Function | C Programming Example",
"Count The Digits In An Integer Number | C Programming Example",
"Find The Frequency Of Digits In An Integer Number | C Programming Example",
"Print The Last Letter Of Each Word In A String | C Programming Example",
"Print The First Letter Of Each Word In A String | C Programming Example",
"Find First Non-RPSPeating Element In An Array | C Programming Example",
"Generate A Random Character | C Programming Example",
"Count The Uppercase Letters In A String | C Programming Example",
"Count The Lowercase Letters In A String | C Programming Example",
"Count The Spaces In A String | C Programming Example",
"Generate A Random Boolean | C Programming Example",
"RPSPeat A String | C Programming Example",
"Count The Whitespace Characters In A String | C Programming Example",
"Generate A Random String | C Programming Example",
"Loop Through A String Without Using strlen() | C Programming Example",
"Reverse A String Using Pointers | C Programming Example",
"Sum The Digits In A String | C Programming Example",
"Convert Feet To Inches And Feet | C Programming Example",
"Shuffle A String | C Programming Example",
"Print A String Using Recursion | C Programming Example",
"Check If Strings Are Equal Using Recursion | C Programming Example",
"Check If A Character Is In A String Algorithm | C Programming Example",
"Remove First Occurrence Of A Character From A String | C Programming Example",
"Remove Last Occurrence Of A Character From A String | C Programming Example",
"Remove All Punctuation Marks From A String | C Programming Example",
"Convert Seconds To Days, Hours, Minutes and Seconds | C Programming Example",
"Print A String In Reverse | C Programming Example",
"Remove The Last Character In A String | C Programming Example",
"Check If Two Arrays Are Equal Or Not | C Programming Example",
"Sum Array Elements Using Recursion | C Programming Example",
"Count The Occurrences Of A Value In An Array Using Recursion | C Programming Example",
"Print Positive Numbers In An Array | C Programming Example",
"Print Even Numbers In An Array | C Programming Example",
"Append A Character To A Dynamically Allocated String | C Programming Example",
"Append A Character To A String | C Programming Example",
"Print Negative Numbers In An Array | C Programming Example",
"Count Even Numbers In An Array | C Programming Example",
"Count Even And Odd Numbers In An Array | C Programming Example",
"Count The Positive, Negative And Zero Numbers In An Array | C Programming Example",
"Print Odd Numbers In An Array | C Programming Example",
"Count Odd Numbers In An Array | C Programming Example",



  ];

  const videoData = videoIDs.map((id, i) => ({
    id: i + 1,
    title: `PSP Video ${i + 1}`,
    thumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`,
    videoUrl: `https://www.youtube.com/embed/${id}`,
    description: videoDescriptions[i] || ""
  }));

  const [selectedVideo, setSelectedVideo] = useState(null);
  const [selectedSection, setSelectedSection] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const openVideo = (v) => setSelectedVideo(v);
  const closeVideo = () => setSelectedVideo(null);

  const renderSection = (key, title, start, end) => (
    <section id={key} className="mb-12">
      <h2 className="text-2xl font-bold mb-4">{title}</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
        {videoData.slice(start, end).map((video) => (
          <div
            key={video.id}
            onClick={() => openVideo(video)}
            className="bg-gray-800 rounded-lg shadow-lg cursor-pointer transform hover:scale-[1.02] transition duration-300 flex flex-row items-start p-3 sm:flex-col sm:p-4"
          >
            <div className="flex-shrink-0 w-2/5 sm:w-full">
              <img
                src={video.thumbnail}
                alt={video.title}
                className="w-full aspect-video object-cover rounded"
              />
            </div>
            <div className="flex-grow min-w-0 pl-3 sm:pl-0 sm:pt-3">
              <h3 className="text-sm sm:text-base font-semibold mb-1 line-clamp-2">
                {video.title}
              </h3>
              <p className="text-xs sm:text-sm text-gray-400 line-clamp-2">
                {video.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );

  return (
    <div className="flex bg-black text-white w-full min-h-screen">
      {/* SIDEBAR */}
      {sidebarOpen && (
        <aside className="fixed top-0 right-0 h-full w-60 bg-gray-900 border-l border-gray-700 p-4 overflow-y-auto z-40">
          <div className="flex items-center justify-between mb-6">
            <h1 className="text-xl font-bold leading-none">Sections</h1>
            <button
              onClick={() => setSidebarOpen(false)}
              className="text-white text-xl font-bold leading-none hover:text-red-500 transition"
            >
              ✖
            </button>
          </div>
          <nav className="space-y-4">
            {[
              ["Complete course", "Complete course", 0, 172],
              ["One shot", "One shot", 172, 173],
              // ["semiconductor", "Semiconductor", 96, 101],
              ["problems", "Problems", 173, 500],
            ].map(([key, label]) => (
              <button
                key={key}
                onClick={() => setSelectedSection(key)}
                className={`w-full text-left px-3 py-2 rounded transition-all duration-500 ${
                  selectedSection === key
                    ? 'bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text'
                    : 'text-white hover:bg-gradient-to-r hover:from-purple-400 hover:via-pink-500 hover:to-red-500 hover:bg-clip-text hover:text-transparent'
                }`}
              >
                {label}
              </button>
            ))}
          </nav>
        </aside>
      )}

      {/* CONTENT */}
      <main className={`flex-1 pt-4 p-4 sm:p-8 ${sidebarOpen ? 'pr-64' : ''}`}>        
        {/* HEADER WITH INLINE TOGGLE */}
        <div className="flex items-center justify-center mb-6 sm:mb-8 relative">
          <h1 className="text-3xl sm:text-4xl font-bold">Problem Solving with Programming - Video Lectures</h1>
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="absolute right-0 text-3xl sm:text-4xl text-white hover:text-gray-300 transition"
          >
            {sidebarOpen ? '✖' : '⋮'}
          </button>
        </div>

        {selectedSection === null && renderSection("Complete course", "Complete course ", 0, 172)}
        {selectedSection === null && renderSection("One shot", "One shot ", 172, 173)}
        {/* {selectedSection === null && renderSection("semiconductor", "Semiconductor Physics", 96, 101)} */}
        {selectedSection === null && renderSection("problems", "Problem Solving", 173, 500)}

        {selectedSection === "Complete course" && renderSection("Complete course", "Complete course ", 0, 172)}
        {selectedSection === "One shot" && renderSection("One shot", "One shot ", 172, 173)}
        {/* {selectedSection === "semiconductor" && renderSection("semiconductor", "Semiconductor Physics", 96, 101)} */}
        {selectedSection === "problems" && renderSection("problems", "Problem Solving", 174, 500)}
      </main>

      {/* VIDEO MODAL */}
      {selectedVideo && (
        <div className="fixed inset-0 bg-black bg-opacity-90 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-900 p-4 sm:p-6 rounded-lg w-full max-w-3xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4 gap-2">
              <h2 className="text-xl sm:text-2xl font-semibold truncate">
                {selectedVideo.title}
              </h2>
              <button
                onClick={closeVideo}
                className="text-white text-lg hover:text-red-500 transition flex-shrink-0"
              >
                ✖
              </button>
            </div>
            <div className="w-full aspect-video mb-4">
              <iframe
                className="w-full h-full rounded"
                src={selectedVideo.videoUrl}
                title={selectedVideo.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>
            <p className="text-gray-300 text-sm sm:text-base">
              {selectedVideo.description}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default PSP;
